### ISSUE TITLE
Issue in the brochure example chat app

### ISSUE THREAD

**Issue by kilburn** [thenativeweb/wolkenkit#112]
At the bottom of page 48 of the  [brochure](https://docs.wolkenkit.io/downloads/wolkenkit-brochure.pdf)  there's an example snippet on how to compute the number of likes of a message:

```javascript
message.events.publish('liked', {
    likes: message.state.likes + 1
});
```

This immediately triggered my spider senses. What happens when two such events are published "simultaneously". That is, what happens if a second like command arrives for a message before the first one's liked event is processed by the handler?

Is there anything in wolkenkit that makes this a non-issue? Is this a bug in the example app waiting to be discovered?

I think it would be interesting for the brochure to address this question

**Comment by goloroden** [comment]
> "Is there anything in wolkenkit that makes this a non-issue?"

Yes 😉 

Actually, commands are run sequentially, at least on a per-aggregate base. I.e., for a single message, multiple commands will always be handled in the correct order (and their according events as well).

But yes, I agree, that it would be a good idea to have a hint on this in the documentation. However, the brochure needs to be updated anyway, as it still uses the old API that refers to wolkenkit 1.x and does not yet use the `async`/ `await` syntax introduced in 2.0.
