### ISSUE TITLE
Invalid user claims key causes domain events can't be persisted by MongoDB

### ISSUE THREAD

**Issue by purefun** [thenativeweb/wolkenkit#1126]
### What is this bug about?

MongoDB as domain event store will raise the error:

`Error: key https://token.invalid/is-anonymous must not contain '.'`

### What steps are needed to reproduce the bug?

1. npx wolkenkit@4.0.0-ctp.5 init chat
2. select one of chat templates
3. set env variables, `DOMAIN_EVENT_STORE_TYPE=MongoDb`, `DOMAIN_EVENT_STORE_OPTIONS=...`
4. send a command
```
curl -H 'content-type: application/json' \
  -d '{"text": "Hello"}' \
http://localhost:3000/command/v2/communication/message/008575b6-e570-4349-9921-49bedf444086/send
```

### What else should we know?

![image](https://user-images.githubusercontent.com/3140656/88265177-99f63e00-ccff-11ea-88c5-54892f903f37.png)

I found this is the original cause:

https://github.com/thenativeweb/limes/blob/master/lib/Limes.ts#L194

and the command:
```jsonc
{
  command: {
    //...
    id: 'f10bad0c-cfdd-47b9-90f2-983d53cc4aac',
    metadata: {
      causationId: 'f10bad0c-cfdd-47b9-90f2-983d53cc4aac',
      correlationId: 'f10bad0c-cfdd-47b9-90f2-983d53cc4aac',
      timestamp: 1595492843192,
      client: {
        token: 'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJodHRwczovL3Rva2VuLmludmFsaWQvaXMtYW5vbnltb3VzIjp0cnVlLCJpYXQiOjE1OTU0OTI4NDMsImV4cCI6MTU5NTQ5NjQ0MywiaXNzIjoiaHR0cHM6Ly90b2tlbi5pbnZhbGlkIiwic3ViIjoiYW5vbnltb
3VzIn0.',
        user: {
          id: 'anonymous',
          claims: {
            'https://token.invalid/is-anonymous': true,
            iat: 1595492843,
            exp: 1595496443,
            iss: 'https://token.invalid',
            sub: 'anonymous'
          }
        },
        ip: '::ffff:127.0.0.1'
      },
      initiator: {
        user: {
          id: 'anonymous',
          claims: {
            'https://token.invalid/is-anonymous': true,
            iat: 1595492843,
            exp: 1595496443,
            iss: 'https://token.invalid',
            sub: 'anonymous'
          }
        }
      }
    }
  }
}
```

**Comment by goloroden** [comment]
@purefun Thanks for the hint! We'll fix this for the next CTP.

**Comment by goloroden** [comment]
@purefun We're able to reproduce this issue, however its cause is slightly different…

Custom claims in JWTs shall be namespaced according to the JWTs' RFC, and it considered a good practice to use URLs for these namespaces, e.g. see https://auth0.com/docs/tokens/guides/create-namespaced-custom-claims

So, the problem is not caused by limes, it's rather that MongoDB is not able to handle keys with dots in them. We are going to think of a way to fix this…
