### ISSUE TITLE
This MongoDB deployment does not support retryable writes.

### ISSUE THREAD

**Issue by purefun** [thenativeweb/wolkenkit#1138]
### What is this bug about?

The events can't be persisted when setting up MongoDB as domain event store.

### What steps are needed to reproduce the bug?

1. `npx wolkenkit@4.0.0-ctp.5 init chat` select chat template
2. `npm install`
3. Comment out `node_modules/limes/build/lib/Limes.js:131` to fix #1126 
4. start the application successfully
```shell
DOMAIN_EVENT_STORE_TYPE=MongoDb \
DOMAIN_EVENT_STORE_OPTIONS='{"hostName":"localhost","port":27017,"userName":"root","password":"root","database":"event_store","collectionNames":{"domainEvents":"domain_events","snapshots":"snapshots"}}' \
npx wolkenkit dev
```
5. send a command
```shell
curl \
    -i \
    -X POST \
    -H 'content-type: application/json' \
    -d '{"text":"Hello, world!"}' \
    http://localhost:3000/command/v2/communication/message/d2edbbf7-a515-4b66-9567-dd931f1690d3/send
```
6. It will emit a failed event with reason: 
```jsonc
// Fetched and locked domain event for flow execution. (debug)
// Nil-mbp.local::chat@0.0.1::wolkenkit@4.0.0-ctp.5 / // (/Users/Nil/Playground/chat/node_modules/wolkenkit/build/lib/runtimes/singleProcess/processes/main/flow/processDomainEvent.js)
11:34:45.473@2020-07-24 88942#36
{
  contextIdentifier: {
    name: 'communication'
  },
  aggregateIdentifier: {
    name: 'message',
    id: 'd2edbbf7-a515-4b66-9567-dd931f1690d3'
  },
  name: 'sendFailed',
  data: {
    reason: 'This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.'
  },
  id: '0b6b35dd-de36-4e43-86ad-752432a20154',
  metadata: {
    causationId: 'bc18f3e2-60ca-4fe8-bc9d-0ba71415ccf3',
    correlationId: 'bc18f3e2-60ca-4fe8-bc9d-0ba71415ccf3',
    timestamp: 1595561684494,
    initiator: {
      user: {
        id: 'anonymous',
        claims: {
          iat: 1595561683,
          exp: 1595565283,
          iss: 'https://token.invalid',
          sub: 'anonymous'
        }
      }
    },
    revision: 2,
    tags: []
  }
}
```

### What else should we know?

The `sendFailed` event will be emitted infinitely.
MongoDB version: 4.2.8
According to the official document, I had set the MongoDB URL with `retryWrites=false` manually.

![image](https://user-images.githubusercontent.com/3140656/88364331-19921480-cdb5-11ea-86d2-10256c52dcfd.png)

**Comment by purefun** [comment]
IMHO, Making the database connection configuration as a URL is more conventional and flexible.

**Comment by purefun** [comment]
https://docs.mongodb.com/manual/core/retryable-writes/#retryable-writes-and-multi-document-transactions

> The transaction commit and abort operations are retryable write operations. If the commit operation or the abort operation encounters an error, MongoDB drivers retry the operation a single time regardless of whether retryWrites is set to false.

As storing domain events is a transaction commit, how to setup `DOMAIN_EVENT_STORE_OPTIONS`?

**Comment by purefun** [comment]
> IMHO, Making the database connection configuration as a URL is more conventional and flexible.

When connecting to MongoDB Atlas, It needs such a MongoDB URL:
```
mongodb+srv://root:xxxxxx@cluster0-3nyft.gcp.mongodb.net/event_store?authSource=admin&replicaSet=Cluster0-shard-0&readPreference=primary
```
There are so many options that can be set via connection URL string.

Furthermore, with the transaction commit, Wolkenkit can only connect to a replica set.

**Comment by yeldiRium** [comment]
> Furthermore, with the transaction commit, Wolkenkit can only connect to a replica set.

This is correct and currently one of the limitations of our implementations, since we wanted to always use transactions for write safety.

(We'll look and the issue as a whole more later, just wanted to throw that piece of information out there.)
