### ISSUE TITLE
Rethink nested mutations for sending commands

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#1139]
### What is this task about?

Right now when sending a command via GraphQL, we use nested mutations. However, this is [not without issues](https://www.freecodecamp.org/news/beware-of-graphql-nested-mutations-9cdb84e062b5/). Originally we said that we don't mind, given the fact that it will be probably be a quite rare issue, and there's a simple workaround. However, maybe we have modeled the GraphQL API to close to the vanilla HTTP one (think of flows, where the command services also does not follow this structure, so we might break it for GraphQL, too). To cut it short, we should rethink the mutation endpoint.

### What needs to be done to complete this task?

- [x] Rethink whether to change the GraphQL mutation endpoint
- [x] Adjust it if we come to the decision to change it
- [x] Update tests
- [x] Update documentation

### What else should we know?

This issue was brought up in Slack by Antonio Mayrinck Moura, so we should notify him of the result.

**Comment by nthypes** [comment]
Thanks for create the issue @goloroden ! I also will research more about the cons side effects of nested mutations.

**Comment by nthypes** [comment]
https://spectrum.chat/graphql/general/namespacing-mutation-types-sub-resources~a4b7f109-ef4e-4079-9336-48be4524d888?m=MTU2NDY3OTY4ODQ4Nw==

Another interesting comment about side-effects of such approach.

`"Additionally it's possible (though unusual) for a mutation to alter the query context."`

**Comment by goloroden** [comment]
We have discussed this internally, and come to the conclusion that we are going to stay with the current (nested) solution, albeit its downsides.

The main reason for this is that it gives us a way better option for auto-completion, e.g. that you have the correct schema for the data of each single command type. If we just had a single `issueCommand` mutation, this validation could not be done any more, at least not on the GraphQL level, which dramatically reduces DX.

However, to avoid the problem you mentioned, we will adjust the GraphQL endpoint in a way that it doesn't allow multiple commands to be send as part of a single mutation. This allows us to become safe, but stay with the comfortable approach.
