### ISSUE TITLE
Client has missing babel-runtime dependency when running in node.js

### ISSUE THREAD

**Issue by arthur5005** [thenativeweb/wolkenkit#116]
Perhaps my node is a little rusty and I'm missing a build step, but I thought I could just npm install this into a fresh app and use it. 
* Node version: 11.3.0

I NPM inited
npm installed wolkenkit-client@3.0.0

Created an index.js with:
```
const wolkenkit = require('wolkenkit-client');
```

Tried to run that and got:
```
node index.js
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/classCallCheck'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    ...
```

Dependency issue, or am I missing something?

**Comment by arthur5005** [comment]
No worries! Installing babel-runtime did the trick, I'm off to the races again. Thanks again :D .

**Comment by goloroden** [comment]
@arthur5005 We have released the client SDK `3.0.1`, which (hopefully) fixes the bug … would you mind testing it again, and letting us know whether it works?

**Comment by goloroden** [comment]
@arthur5005 Ping 😉

**Comment by goloroden** [comment]
@arthur5005 Since we haven't heard anything back from you, we assume that everything now works as expected, and hence I am going to close this issue now. If there are any other things you experience, please open a new issue.
