### ISSUE TITLE
Expose HTTP ports to enable mobile testing

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#117]
### What is this feature about?

Right now we only expose the HTTPS ports, which makes testing for mobile devices cumbersome. We should introduce a new flag to the CLI, something such as `--dangerously-expose-http-port` to also expose the HTTP ports, so that you can test using your local machine without any certificate issues. We also need to adjust this in the client SDK, as it currently only supports HTTPS, but not HTTP.

### What needs to be done to implement this feature?

- [x] Update the CLI
  - [x] Introduce a new flag to enable exposure of HTTP ports
  - [x] Configure the proxy accordingly
  - [x] Add tests
- [x] Update the client SDK
  - [x] Introduce an HTTP wire
  - [x] Add tests
- [ ] Update the documentation

**Comment by jbeaudoin11** [comment]
Hey @goloroden would like to know if we could add this fast to wolkenkit ? Or give me indications how to do it temporarily ? I don't see any PR or branch associated to this so it's hard to know how to do it. It looks like the feature is completed but only docs is missing ?

**Comment by goloroden** [comment]
Try running `wolkenkit start --help` 😉 

The current CLI already has these flags built-in, it's just not yet officially available. But it should work since `3.1.0`. 

The reason why it is not yet documented and not yet officially supported is that the client SDK does not support http right now, only https or wss. So this means that you may have to adjust your client code, but apart from that things should work.

We are currently working on a new client, which has been rewritten from scratch entirely. This will then include http support.

**Comment by jbeaudoin11** [comment]
![image](https://user-images.githubusercontent.com/10903391/55180544-2e7a7b80-5160-11e9-94ba-6091e4a0b3f2.png)

Oh, the flag is `--dangerously-expose-http-ports` with an **s** at the end. There is inconsistency in the help, in the synopsis it doesn't take an **s** but in options it does

**Comment by goloroden** [comment]
https://github.com/thenativeweb/wolkenkit/commit/5d848ddc8fac5ab1bf3677ebe054d4c9bfa9ffcb 😉

**Comment by goloroden** [comment]
This one becomes obsolete by #280, hence closed.
