### ISSUE TITLE
Union types in GraphQL Schema

### ISSUE THREAD

**Issue by dfeyer** [thenativeweb/wolkenkit#1175]
Given the following schema: `id: { type: ["string", "integer"] },` I have the following error:

`Union type Context_aggregate_commandT0id can only include Object types, it cannot include String.`

I looks like a limitation in GraphQL schema

**Comment by goloroden** [comment]
This actually seems like a limitation of GraphQL, see [this source](https://graphql.org/learn/schema/#union-types):

> Note that members of a union type need to be concrete object types; you can't create a union type out of interfaces or other unions.

The first part of the sentence is relevant here: As `string` and `integer` are no object types, they don't work.

Hence closed.

**Comment by dfeyer** [comment]
@goloroden Yes I know it's a graphql limitation, but if it's supported by JSON Schema and works fine for the non-graphql API... so from.a Wolkenkit point of view, limitation of GraphQL are kind of "enforced" ... what do you think about my proposition to have an optional GraphQL support ? And if enable, then we should make the application JSON schema compatible ?

An other improvement can be to have those warning at build time to avoid shipping in production a broken app. Actually this exception is thrown only when starting the application.

**Comment by goloroden** [comment]
@dfeyer Ah, okay, I'm sorry, I didn't get this from the issue.

If you disable GraphQL support the problem should be gone (please note that GraphQL is enabled by default in `dev` mode).

Nevertheless, we might add a GraphQL schema validation on startup, hence I've reopened this issue.
