### ISSUE TITLE
Update the package.json schema

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#118]
### What is this task about?

We should perform a few changes to the `package.json` schema, to better reflect a number of things. The changes affect the `host`, the `port`, the `certificate`, and the `name` of the identity provider. They should become:

- `api.host` (optional)
  - `api.host.name` (mandatory)
  - `api.host.certificate` (mandatory)
- `api.port` (optional)
- `identityProvider` (optional)
  - `identityProvider.issuer` (mandatory)

### What needs to be done to complete this task?

- [x] Improve the way the configuration gets loaded and merged
- [x] Perform the changes to the schema
- [x] Adjust tests
- [x] Adjust documentation

**Comment by grundhoeferj** [comment]
PR: https://github.com/thenativeweb/wolkenkit/pull/124
