### ISSUE TITLE
How to write tests?

### ISSUE THREAD

**Issue by gossi** [thenativeweb/wolkenkit#119]
### What is this question about?

Given I do have a flow, how do I write tests for it so I have unit tests that prooves it's functionality?

**Comment by yeldiRium** [comment]
Basically we'd have to write an integration testing framework for the wolkenkit. Since we have in-memory variants of all stores, it should be possible to provide some apis that enable better testing of wolkenkit applications without starting the whole thing.

**Comment by goloroden** [comment]
Superseded by #344, hence closed.
