### ISSUE TITLE
Fix Docker-Compose files to match new configuration objects

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#1212]
### What is this bug about?

For `4.0.0-internal.63` we changed the format how stores get configured. Apparently we forgot to adjust the Docker Compose files accordingly, because if you try to start the micro-service runtime, you get an exception telling you:

> Missing required property: type (at consumerProgressStoreOptions.type).

We need to fix this.

### What is the expected result?

The micro-service runtime should start with the Docker-Compose file.

### What is the actual result?

The micro-service runtime does not start with the Docker-Compose file, and crashes instead with the aforementioned error.

### What steps are needed to reproduce the bug?

- Set up an application with `4.0.0-internal.63` (probably, also newer versions are affected).
- Try to start it with the micro-service runtime.

### What else should we know?

This issue has been brought up by Igor, so we should notify him once this has been done.

**Comment by yeldiRium** [comment]
This seems to be fixed with #1213. I've tested all manifests.
