### ISSUE TITLE
Support object rest operator

### ISSUE THREAD

**Issue by mattwagl** [thenativeweb/wolkenkit#122]
### What is this bug about?

It's currently not possible to use the object rest operator in a wolkenkit application.

### What steps are needed to reproduce the bug?

-  init a sample application
- Add the following code to the `sampleCommand`

```javascript
async sampleCommand (sampleAggregate, command) {
    const sampleObject = { ...command.data };
    
    sampleAggregate.events.publish('sampleEvent', {
      // ...
    });
  }
```
- run `wolkenkit start`

### What is the expected result?

The application should start.

### What is the actual result?

The CLI fails to start with the following output:

```shell
  Starting the application...
  
/Users/matthiaswagler/Dev/tnw/temp/destructuring-test/server/writeModel/sampleContext/sampleAggregate.js
  17:28  error  Parsing error: Unexpected token ..

  1 problem (1 error, 0 warnings)
✗ Failed to start the application.

```

### What else should we know?

Seems like the linter which checks the application before starting it, does not support the spread operator for objects. It's available [since Node 8.6](https://node.green/#ES2018-features-object-rest-spread-properties). So it should be save to enable.

**Comment by goloroden** [comment]
The reason for ESLint flagging this as a problem is that the spread operator is only part of ES2018, which we did not yet enable. Node.js supported it much earlier than it was officially released, but we could (probably) easily change this.

**Comment by goloroden** [comment]
PS: It's [this line](https://github.com/thenativeweb/wolkenkit-box-esvalidator/blob/master/eslint/configuration.json#L3) that needs to be updated.

**Comment by goloroden** [comment]
Of course it was a different place, as we don't use the ESLint image any more. Instead, the CLI cares about validating the code by itself – however, I'm going to fix it there.

**Comment by mattwagl** [comment]
Thanks for fixing this so quickly!
