### ISSUE TITLE
Support updating an object inside of an array

### ISSUE THREAD

**Issue by mattwagl** [thenativeweb/wolkenkit#123]
### What is this feature about?

In our application we're creating a list where each item holds an array of files. Each file is identified by its url. Now when an particular event arrives we want to update a particular file in that array using the url. We currently do it like this:

```javascript
const fields = {
  files: { initialState: []}
};

const projections = {
  'xxx.xxx.fileAdded' (list, event) {
    list.add({
      files: [{ url: event.data.url }]
    });
  },

  async 'xxx.xxx.fileAnalysed' (list, event) {
    const { url, additionalProperty } = event.data;

    const itemToUpdate = await list.readOne({
      where: { id: event.aggregate.id }
    });

    const newFiles = itemToUpdate.files.map(file => {
      if (file.url !== url) {
        return file;
      }

      return {
        url: file.url,
        additionalProperty
      };
    });

    list.update({
      where: { id: event.aggregate.id },
      set: {
        files: newFiles
      }
    });
  }
};
```

Would be great if this could be written more easily. [Seems like mongoDb is able to handle this](https://docs.mongodb.com/manual/reference/operator/update/positional-filtered/#positional-update-arrayfilters). But we would need to come up with an API that could translate into these features.

### What needs to be done to implement this feature?

- [ ] Get some feedback from the community, if this feature is needed/useful
- [ ] Come up with an API
- [ ] Implement the feature

**Comment by goloroden** [comment]
This will be solved by #148, hence closed.
