### ISSUE TITLE
Events may not get ordered correctly

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#131]
### What is this bug about?

When storing events in the event store, we write a `position` field to get a global ordering for replaying. Until now we assumed that this is safe, since the `position` is incremented automatically (except in MongoDB), and we assumed that accessing the sequence is safe due to the surrounding transaction. As it turns out, this is *not* the case (see [this StackOverflow question](https://stackoverflow.com/questions/2095917/sequences-not-affected-by-transactions) for details). Unfortunately, this not only affects PostgreSQL, but basically all databases we support.

A simple way to solve this issue would be to acquire a table lock, but this is pretty expensive. As a cheap alternative, we may use `advisory locks`, which exist for all relational databases we support:

- [PostgreSQL](https://www.postgresql.org/docs/9.4/explicit-locking.html#ADVISORY-LOCKS)
- [SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-getapplock-transact-sql?view=sql-server-2017)
- [MySQL](https://dev.mysql.com/doc/refman/8.0/en/locking-functions.html#function_get-lock)
- [MariaDB](https://mariadb.com/kb/en/library/get_lock/)

In MongoDB, there is no such lock concept, but since MongoDB doesn't have auto incrementing fields anyway, we need a different approach here. We currently assume that if we introduced transactions for MongoDB, things would work (also see #65).

### What steps are needed to fix the bug?

- [x] Decide whether to use advisory locks or table locking
- [x] Implement locking for relational databases
- [ ] Define a way how to deal with this in MongoDB
- [ ] Implement locking in MongoDB

### What else should we know?

This bug was brought up by @rkaw92 on Slack, and we should notify him once we have solved this issue (he's also on [Twitter](https://twitter.com/rkaw92)).

**Comment by AlexZeitler** [comment]
Is this problem currently being actively addressed?

**Comment by goloroden** [comment]
Right now, no. We're currently in the middle of migrating the codebase to TypeScript.

Could you imagine coming up with a PR?
(If so, before you start, please let's discuss a few things.)

**Comment by AlexZeitler** [comment]
Yes, I’ve seen the TS PR 😉

We’re using MongoDb as an ES and we’re facing similar issues.
I’ve been digging into DynamoDb as an ES recently and there it will happen as well I guess.

In general I’m open for a PR and discussion.

**Comment by goloroden** [comment]
That's great, thank you 😊

As said, we are currently migrating the codebase to TypeScript. Hence, this issue should be fixed in the branch `monorepo-typescript`, not in `master`. Yesterday, we introduced [an interface for the event stores](https://github.com/thenativeweb/wolkenkit/blob/monorepo-typescript/src/stores/eventstore/Eventstore.ts), and we moved the [in-memory event store](https://github.com/thenativeweb/wolkenkit/blob/monorepo-typescript/src/stores/eventstore/InMemory/index.ts) to TypeScript. This means that the other event stores have to be migrated to TypeScript first, which will probably done within a few days.

Now basically, if you want to help us with some code, this brings up two options:

- You could either wait until we have done the migration, and then create a PR with the changes required for this issue.
- Or you could migrate the store implementations on your own, against the given interface, and directly integrate the changes for this issue.

If you decided for option two, we could migrate the tests in parallel, which would speed up things slightly. But it's also perfectly fine if you say that you would rather like to wait.

What do you think about this in general?

**Comment by goloroden** [comment]
@AlexZeitler Ping 😉

**Comment by AlexZeitler** [comment]
👋 Is there a thread which describes the current issues or a test for repro?

**Comment by goloroden** [comment]
Unfortunately, neither nor. The only thing we have right now is this issue.

Respectively, there was a little discussion on this in Slack, see https://wolkenkit.slack.com/archives/C1D614Q0P/p1549914838010800

**Comment by AlexZeitler** [comment]
Thanks, will catch up on the Slack discussion and come back with further questions/ suggestions.

**Comment by AlexZeitler** [comment]
Btw whats the state of the TS-Migration for the Eventstores?

**Comment by goloroden** [comment]
There are two interfaces defined - one for the [eventstore](https://github.com/thenativeweb/wolkenkit/blob/monorepo-typescript/src/stores/eventstore/Eventstore.ts) itself, one for [snapshots](https://github.com/thenativeweb/wolkenkit/blob/monorepo-typescript/src/stores/eventstore/Snapshot.ts). In addition, the [in-memory](https://github.com/thenativeweb/wolkenkit/tree/monorepo-typescript/src/stores/eventstore/InMemory) provider has been migrated. The other ones haven’t yet. 

The tests are partially migrated - we are currently adding TypeScript support to our build tool, but we will get back to this in a few days.

**Comment by AlexZeitler** [comment]
I guess it it would make sense to first migrate the eventstores, then fix them.

**Comment by goloroden** [comment]
Sounds reasonable 👍

**Comment by goloroden** [comment]
PS: If you want to help us with this, it would make sense to get @yeldiRium into the loop, as he knows most about the migration and its status.

**Comment by AlexZeitler** [comment]
Ok

**Comment by yeldiRium** [comment]
Slight excursion regarding the migration status:

The `InMemoryEventstore` is migrated, because it was necessary to test the rest around it. The other `Eventstores` haven't been touched yet.
The main reason for that is that there are no meaningful (at least with TypeScript) unit-tests for them, since the old unit tests all just checked for errors when parameters were missing etc. There are, however, quite a few integration tests for the eventstores, the execution of which depends on the [roboter](https://github.com/thenativeweb/roboter) supporting TypeScript. [This is in the works.](https://github.com/thenativeweb/roboter/tree/add-typescript-support)
After the roboter successfully supports TypeScript (which should be done sometime during next week) we will integrate the new version in the `monorepo-typescript` branch.

Then we can start migrating the integration tests for the eventstores and the eventstores themselves. If someone wants to participate in that migration I can leave note here once we are at that point and we can coordinate our efforts.

The `Eventstores` could, of course, be migrated earlier without regard for the tests. But I wouldn't want to do so in the `monorepo-typescript` branch and rather in a separate branch so that we can test that branch against the integration tests once those are ready.

**Comment by AlexZeitler** [comment]
Thanks for the explanation. So I think the best way to get stuff done is - as you suggested - that you ping me here when we can start migrating tests and stores altogether.

**Comment by yeldiRium** [comment]
Soo, migrating the roboter (and more than that testing it) took a little longer than expected, but is finished now.

I will now clean up the current state of the wolkenkit typescript migration to a point where the already migrated tests succeed and where the code styles match those of the new eslint rules we established.

Then I'll ping here again and we can start with the stores.

**Comment by goloroden** [comment]
@AlexZeitler Sorry for the quite long delay – we finally made it: The migration of the monorepo code base to TypeScript is now done, and the tests are working again. Not all of the wolkenkit code is in the monorepo yet, but at least all of the stores are, and you can test them 🎉

So, if you are still interested, we would be more than happy if you would like to work on this bug fix 😊 

What do you think?

**Comment by goloroden** [comment]
Since we have decided to get rid of the global revision entirely, and we only ensure ordering inside of aggregates, we don't have this problem any longer, and so we don't need to fix this any more. Hence closed.

**Comment by nowakprojects** [comment]
@goloroden What about projections from EventStore right now? You get rid of global ordering, but it's needed to make projection from more-than one aggregate.

**Comment by goloroden** [comment]
Right now we don't support EventStore.

The strategy to have projections across more than one aggregate is *currently* to solve it within the query on the server-side. This will not be our long-term strategy, but for now it was the best trade-off.
