### ISSUE TITLE
Improve error output when a CLI command fails

### ISSUE THREAD

**Issue by mattwagl** [thenativeweb/wolkenkit#135]
### What is this concept about?

Currently when a CLI command like `wolkenkit start` fails, there is no output about the actual error that caused the command to fail. This is very annoying and also makes failing commands harder to debug as you need to run them again.

I think we should switch this default behaviour. So when an error occurs, the details about this error should always be displayed, just like when running in `verbose` mode.

### What issues need to be clarified to complete this concept?

- [x] Figure out if this somehow may cause issues with `--verbose` mode
- [x] Enable error output for failing commands in the CLI

**Comment by goloroden** [comment]
This is pretty easy to implement – all we need to do is to enable verbose mode if an error happens and verbose mode is not (yet) active.

I'm going to implement this soon.
