### ISSUE TITLE
Support encrypted connections to the event store

### ISSUE THREAD

**Issue by manfredmjka** [thenativeweb/wolkenkit#140]
### What is this feature about?

Some PostgreSQL servers (such as the managed ones on Azure) force you to use SSL encrypted connections, which is currently not supported by the eventstore, since the appropriate option is [not passed](https://github.com/thenativeweb/wolkenkit-eventstore/blob/46bdd8bdb93d4fa3be20f7c3f15234060044c796/src/postgres/Eventstore.js#L38) to the `pg` driver. This should be changed.

### What needs to be done to implement this feature?

- [x] Add an option to indicate that SSL encryption is required
- [x] Adjust the tests
- [x] Update the documentation

**Comment by goloroden** [comment]
Hi @manfredmjka 😊 

Thanks a lot for bringing up this issue! I have updated your original post with a few information, and I moved it to another repository. I hope this is fine for you.

We will notify you once we have done this!

**Comment by manfredmjka** [comment]
Are there any updates on this? 
I thought maybe solving this issue by myself to fix this faster, because we need this asap. 

Are there any requirements on the implementation side? 

I see the issue that just passing the ssl option is not enough there. What about using custom certificates and custom CA? 
The way how its implemented at the moment (just parsing the connection string) makes it hard to pass actual certificates to `initialize` function. Any ideas how to solve this properly?

**Comment by goloroden** [comment]
For now, unfortunately, there is no update yet.

Could you imagine submitting a PR? If so, we could talk about a few things we have in mind, and see how we can put your needs and our ideas together 😊

**Comment by goloroden** [comment]
Version 2.6.0 is on npm 🎉
