### ISSUE TITLE
Introduce function-based authorization

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#146]
### What is this feature about?

Right now, authorization is configured using an object. It would be way more flexible if this was done using a function that is called to get the actual authorization options for a command or an event. The same approach could then be implemented for the read model and the file storage.

### What needs to be done to implement this feature?

- [x] Update the core
  - [x] Replace the existing authorization mechanism
  - [x] Update tests
- [x] Update the broker
  - [x] Replace the existing authorization mechanism
  - [x] Update tests
- [x] Update the CLI
  - [x] Update dependencies
  - [x] Drop support wolkenkit < 4
- [ ] Update flows
  - [ ] Update impersonation
- [ ] Update the file storage
  - [ ] Replace the existing authorization mechanism
  - [ ] Update tests
- [ ] Update the client SDK
  - [ ] Update impersonation
- [ ] Run a few real-world tests
  - [ ] Boards
  - [ ] Never completed game
- [ ] Introduce backwards compatibility layer
  - [ ] For `transferOwnership`
  - [ ] For `authorize`
- [ ] Update documentation

### What else should we know?

This issue was brought up by @schmuto, so we should notify him once this has been done.

**Comment by goloroden** [comment]
The new API could look like the code in the following sections.

### Write model, commands

```javascript
rename: {
  schema: {
    type: 'object',
    properties: {
      title: { type: 'string', minLength: 1 }
    },
    required: [ 'title' ]
  },

  // isAuthorized: forAuthenticated(),
  // isAuthorized: forPublic(),
  isAuthorized (board, command) {
    return command.user.id !== 'anonymous';
  },

  // filter: board => exists(board) && !isDiscarded(board),
  filter (board, command) {
    return exists(board) && !isDiscarded(board);
  },

  handle (board, command) {
    board.events.publish('renamed', {
      title: command.data.title,
      slug: createUniqueSlug(command.data.title)
    });
  }
}
```

### Write model, events

```javascript
renamed: {
  handle (board, event) {
    board.setState({
      title: event.data.title
    });
  },

  // isAuthorized: forAuthenticated(),
  isAuthorized (board, event) {
    // ...
  },

  filter (board, event) {
    // return event.user.id !== 'anonymous';
  },

  map (board, event) {
    // return event;
  }
}
```

### Read model

```javascript
const queries = {
  readItem: {
    isAuthorized (board, query) {
      // ...
    },

    filter (board, query) {
      // ...
    },

    map (board, query) {
      // ...
    }
  }
};
```

### File storage

In `services/fileStorage.js`:

```javascript
'use strict';

const commands = {
  addFile: {
    isAuthorized (file, command) {
      // ...
    },

    filter (file, command) {
      return // ...
    },

    map (file, command) {
      const encryptedFile = encrypt(file);

      return encryptedFile;
    }
  },

  renameFile: {
    isAuthorized (file, command) {
      // ...
    }
  }
};

const queries = {
  getFile: {
    isAuthorized (file, query) {
      // ...
    },

    filter (file, query) {
      return // ...
    },

    map (file, query) {
      const decryptedFile = decrypt(file);

      return decryptedFile;
    }
  }
};

module.exports = { commands, queries };
```

**Comment by goloroden** [comment]
Current status, to be continued…

- Core works with new authorization API for commands and events
- Broker is partially done, see `willPublishEvent` function in `appLogic/index`
  - Sending commands should work as defined
  - Handling events is not yet done
  - Read model events do not yet take new authorization concept into account

Next steps:

- Make events and read model events run
- Adjust read model authorization to new API
  - Introduce `readList`
- Make tests run
- Test commands / events with boards
- Flows
  - Special focus on impersonation (`asInitiator` instead of `asUser`)
- File storage
- Client SDK (impersonation!)
  - Update `commands-events`
  - Verify that updating read models works
- CLI
- Documentation

**Comment by jbeaudoin11** [comment]
Just to make sure, isAuthorized can be async right ?

**Comment by mattwagl** [comment]
Yes it can. But of course you need to be careful here. Especially when authorizing events or the readModel, as this can slow down the read performance. What kind of async stuff would you be interested in executing there?

**Comment by jbeaudoin11** [comment]
@mattwagl I'm trying to figure out how to handle permissions, RBAC or/and IBAC...

I can see a Permission aggregate or permission attribute in a User aggregate with an internal view in the readModel which expose those permissions. The isAuthorized function could call that view.

**Comment by mattwagl** [comment]
@jbeaudoin11 The goal of this rewrite is to allow more flexibility for authorization. One way for example would be to add roles as claims to the JWT of the user. Inside the `isAuthorized` function you now have access to the the current state of the resource as the first parameter e.g. the aggregate. As second parameter you get the action that needs to be authorized like a command, an event or a query. As a third parameter you now get `services`. There’s a new `client` service that holds the token of the user that executes this action. So here you could inspect the token for specific roles and return either true or false in order to allow or disallow the action. 

Hope the new API would also support your use case. If not, you can still provide feedback while we‘re working on a this... 😊

**Comment by jbeaudoin11** [comment]
@mattwagl Our use case might need dynamic permissions but what you described is more of a static way to do RBAC.

If i have a view exposing permissions i think it's a good way to deal with this but we must make a call every time someone try to execute an action, which might be expensive, but i don't really see other ways to implement this.

**Comment by goloroden** [comment]
Haha, that would have been my first question - how to approach this in a different way 🤣

However, if you have any ideas or specific use cases you would like to discuss, as @mattwagl already said: Feel free to do so 😊

**Comment by goloroden** [comment]
PS: Regarding dynamic permissions - since you can also access the aggregate and its state, you can dynamically choose what to do. At least, if the aggregate provides the information you need.

**Comment by jbeaudoin11** [comment]
So you suggest that we store permissions in each aggregate ? That could work for commands and maybe events, but not for queries in the readModel

**Comment by goloroden** [comment]
But you could store auth information in the read model, too.

**Comment by jbeaudoin11** [comment]
I don't think permissions should be implemented at the aggregate/domain level. In most cases it won't help us at all and will make things much more complex.

For example, base on the chat demo. User A has the right to execute `communications.message.send` but not user B. How could you do that at the aggregate level ?

What i would rather see is a simple call to the the readModel like
```
async isAuthorized(aggregate, command) {
  return !!await app.lists.permissions.readOne({
    where: { userId: command.user.id, permission: "communications.message.send" }
  })
}
```
I'm kinda of oversimplifying it since there is no role here, but i think you can get the point.

**Comment by goloroden** [comment]
For sure, you have a valid point here.

I wouldn't go so far to say that you should never have authorization information on the aggregate level, since there definitely are scenarios where it makes sense to have this.

But of course, there also may be situations, where you want to separate both things, and then your suggestion to use the read model for this is pretty great! I think that in the end we will allow both. Since you are free to use in the `isAuthorized` function whatever works for you, you can go that way as well. Of course, then we might have to think about performance issues, but let's solve one thing at a time 😊 

Maybe caching then will be interesting, but let's wait and see. However, I think that we will provide a way to query the read model as well, similar to what you can do using the `app` service.

**Comment by jbeaudoin11** [comment]
Another way could be to store the information in the JWT. There is a problem tho, the JWT might not be up to date for a while. Maybe there is a way to force the JWT refresh after a change in permissions, i'm not sure and it's specific to the identity provider.. But this is out of the scope of wolkenkit.. Right ?

**Comment by goloroden** [comment]
I think it depends on the scenario, so I assume there's no 1/0 answer.

Your thoughts about storing data in the JWT are correct: But as you said, this then is out of scope of wolkenkit, and of course it only works for small amounts of data, as otherwise your tokens get very large, which is an additional payload on every request.

**Comment by goloroden** [comment]
Will be part of v4, but the state of the issue is too far from current development, and expectations and plans have changed in so many areas, that it doesn't make sense to keep it open. Hence closed.
