### ISSUE TITLE
How flexible is the read model ?

### ISSUE THREAD

**Issue by jbeaudoin11** [thenativeweb/wolkenkit#148]
### What is this question about?
Hi, I'm new to wolkenkit and while I'm looking around in the doc and on github, some questions popped in my head and i couldn't find anything related to this.

The read model is base on lists and is really close to MongoDB. But what happens if you need something else than lists or if MongoDB isn't really the best tool for the work ? For example a graph database like Neo4J could be better for some use case.. If my app contains a lot of tables with static columns, SQL might be better here.. When i saw #83, why not use ElasticSearch which is designed for text search.

So my questions  :

- What type of database is sported by wolkenkit for the read model ?
- Can we use or is there plans to support multiple databases at the same time for the read model ?
- Would it be easy to create a custom denormalizer for another database ?
  - This probably mean adding another type like lists
  - It also includes streaming data to clients
  
I feel like the read model api is trying to create an abstraction layer with MongoDB but at the same times it doesn't do a good job and give anything more to the developer. Why not juste give direct access to the database or even better remove the database specifics to the api of the read model ?

```javascript
const projections = {
  // ...
  'communication.message.liked' (messages, event) {
    messages.update({
      where: { id: event.aggregate.id },
      set: {
        likes: event.data.likes
      }
    });
  }
};
``` 

Instead it could be something like :

```javascript
const messages = mongoose.model("Messages");

const projections = {
  async 'communication.message.liked' (event) {
    const msg = await messages.updateOne({
      id: event.aggregate.id
    }, {
      $set: {
        likes: event.data.likes
      }
    });

    return msg; // Use this element for streaming ?
  }
};
```
_(bear with me, my mongoose is rusty)_

Of course this would impact the client api, but in the end the whole thing is much more flexible isn't it ? This might be related to #102 and also #90.

### What else should we know?
I haven't build an app yet with wolkenkit, but I'm in the process of.

**Comment by goloroden** [comment]
Hi @jbeaudoin11 😊 

Thanks for bringing up this issue. You are right that currently we only provide an abstraction over MongoDB. Actually, the original idea was that there might be more databases that you can use, and we wanted to make it easy to switch them (this is why we introduced an abstraction layer). Also, since wolkenkit let's you focus on domain code, we wanted to abtrsact away some of the technical details of the underlying database.

Of course, there may be completely different data structures than lists (such as graphs, trees, ...), and for them a completely separate API would be needed, but then again this wouldn't be part of the list API, but we'd have a separate API for this. If I look at how different graph databases work, e.g. to walk through graphs, I think that it highly makes sense to ease and unify these things.

One of your sentences caught my special attention:

> but at the same times it doesn't do a good job and give anything more to the developer

It (currently) does not give you more: Agreed. But "it doesn't do a good job"? What are you missing, or what isn't working as expected? (Please don't take this question as an impeachment, I would actually like to learn about what you think about this!)

**Comment by jbeaudoin11** [comment]
@goloroden Thanks for the reply !

> You are right that currently we only provide an abstraction over MongoDB. Actually, the original idea was that there might be more databases that you can use, and we wanted to make it easy to switch them (this is why we introduced an abstraction layer). Also, since wolkenkit let's you focus on domain code, we wanted to abstract away some of the technical details of the underlying database.

I'm not against an abstraction layer, it does help beginners ! But give us the possibility to chose between it and our own way of storing the read model data. I don't see any documentation about that, if it exist please give me a link !

Maybe I'm wrong but i feel like the domain code is more of a write model thing, there I can agree that you need to enforce some kinda of structure to have a robust and coherent system. But the read model shouldn't care that much about the domain, it's a way to express the state of the system, if you want you can drop it and start from scratch w/o affecting your domain code. Imo it should offer much more flexibility in how you chose to handle your projections. Don't get me wrong, I'm impressed by the framework ! But I feel like the write model got more love than the read model.

> Of course, there may be completely different data structures than lists (such as graphs, trees, ...), and for them a completely separate API would be needed, but then again this wouldn't be part of the list API, but we'd have a separate API for this. If I look at how different graph databases work, e.g. to walk through graphs, I think that it highly makes sense to ease and unify these things.
...
But "it doesn't do a good job"? What are you missing, or what isn't working as expected?

This is my understanding of your goal with the abstraction layer : give an API specific to the data structure, but not specific to the database. This is where I think it doesn't do a good job. For lists, it make sense to go with MongoDB. I feel like the abstraction layer is "okay", the current state of the API is literally imo a smaller copy of the MongoDB/Mongoose API but doesn't let you use the specific features of MongoDB when you want or need it. Which is fine since it's not its goal, but a good example of where it doesn't help is #83. This force us to wait and hope that you guys support it in the API or hack it our self some how. What will happen if you don't use MongoDB for lists ? Some feature might not work well with another database if you start supporting stuff like `$regex` or `$text` and there is nothing similar in the other one... So in the end, the database specific features might not be supported in the abstraction layer and we are back to square one.

Why can't we have access to the database instance and chose how we handle the read model data ourselves ? At least have a way to access the underlying database instance through the API could be nice (front and backend), maybe not directly but via some hooks, I don't know, there's some thinking to do here. Yes that could lead to more bugs in our code and maybe not using the data structure has intended but it's our choice/problem not yours, sometime you have no choice to write some cheesy stuff to save days of work right now and deal with the consequences later. Another valid option, you could force the database for the data structure or have a more specific API... Right now it kinda feels like it's already the case with lists anyway since it's so close to MongoDB.

Like I said in my OP, I haven't done an app with wolkenkit yet, but I'm working on it. Right now the list API is good enough for our current needs, but who knows what will happen in a couple of months... In the end I do understand that you guys are trying to create an API for the data structure and not for the underlying database, but in reality, the two looks very tight coupled and instead of building our query with database specific features, we are blocked by the abstraction layer. For scalability this imo looks very bad since we can't try to optimize our query well.

The more I write about this topic, the more I feel like the problem isn't necessary the list API. It's a good and practical API for most of the task. When needed, we could base our selves on the list API and create our own I guess. I didn't see any documentation on how to write your own data structure, is there an "official" way to do it or is it on the roadmap ?

**Comment by goloroden** [comment]
To be honest, you really got me thinking. Your points are very valid and well observed. And I can’t say anything but that you are absolutely right with #83. 

This week I’m on the road, but I’m going to put this into the current milestone, and we will discuss this next week internally and then get back to you. 

I’m sorry that this now will take a few days. 

However, thank you very much for bringing this up!

**Comment by goloroden** [comment]
@jbeaudoin11 As promised, we have discussed this. We have been thinking this forth and back, and we were close to throwing the entire read model away, and to let the user do all the things with Mongoose or something like that on their own. However, we didn't throw it away 😉 

The main reason for this is that the API provides real-time updates about what has happened in the read model, and that there is a nicely integrated way to access the read model with the client. Both would be lost if you had to roll your own solution.

But we than thought that maybe we could follow the pareto principle here: For 80% of the cases, the existing read model with the abstraction layer is maybe fine, so let's stick with it as it is. For the remaining 20% of the cases it would be great to have an option that allowed for maximum flexibility. What about something such as a *custom read model*, which is basically nothing more than a set of hooks that allow you to run whatever code you want to? This would allow to build a read model using Mongoose, or to use ElasticSearch, or to use a graph database such as ArangoDB, or do whatever you want to do.

This is almost doable already today, by using flows. Actually, the existing read model is just one implementation of a stateless flow, where you react to domain events by accessing a database. What's missing maybe is just a way to let you run initialization code, to ensure that you have a connection, and similar things. Supposed you had this, would this work for you? What do you think about this way?

**Comment by jbeaudoin11** [comment]
Mmmm, maybe what you describe as a custom read model with hooks could work. Could it be possible to do real-time updates too ? When you talk about creating a custom read model and hooks, what i understand is more or less adding hooks not to the read model, but directly on the List API which is not exactly what i'm looking for. Am i wrong ?

> ...we were close to throwing the entire read model away, and to let the user do all the things with Mongoose or something like that on their own...
>
> The main reason for this is that the API provides real-time updates about what has happened in the read model, and that there is a nicely integrated way to access the read model with the client. Both would be lost if you had to roll your own solution.

The thing is, when i saw how you could do real-time updates to the wolkenkit-client i was really happy. It's such an important part in the CQRS implementation and i wouldn't like to lose it or to implement it my self, i don't see any benefits.

What i had in mind was a way to create your own api like the List API, independent of the underlying data structure / database. I don't know how the List API is implemented, but wolkenkit should expose some functions to help you create something like the List API. Exposing real-time communications some how and letting us handle the storage part. Maybe it's already possible, just not documented !

If you look at my example with mongoose, i removed the first param which in the List API is an abstract api build for mongo. If i don't wanna use the List API, i could create, let say a Collection API, i could pass a mongoose model or the full mongoose instance, or event the mongodb driver directly, it's my choice. If someone wanna create a Table API, the first param could be a Sequelize instance.

Also for the client, let me know if i'm wrong, but what the client do is asking for the json configuration and build it's own API with that. I'm sure there is a way to keep all the current client functionalities like readAndObserve with a custom read model API. There is no need to throw all the current read model away, but iterate over it.

**Comment by goloroden** [comment]
The main issue here is that we can't rely on something such as MongoDB's ops log, as this is implemented differently in every single database. Our approach right now is that when you call `add` & co., you only express the *intent* to add, but do not actually modify the database. Instead, you publish events, similar to what you do on the write model side.

Then, once all your read model events have been created, all of the database actions take place in a single shot. We then use the previously created events for the client.

This is why we have to keep those functions, and can not provide you with a direct access to the API of the database, if you want to keep the live update functionality. The question here probably is how to combine this approach with an exchangable database layer below.

Any ideas?

**Comment by jbeaudoin11** [comment]
@goloroden Sorry for the delay !

I think you put too much responsibility to the readModel and not enough in the "API". It should pretty much only handle communications with the client for real time and with events from the writeModel, **not with the database**. What you described is how the List API internally handle inputs (events) and apply a transformation to its database (MongoDB) them ouputs to stream.

What needs to be done is separate external communications from the API. In all cases we get events from the writeModel. The API then take an event and execute a projection associated to this event with what ever arguments the projection needs and returns. If internally the API wanna use MongoDB's ops log to handle real time updates, if it want to pass a service in the argument instead or if it wants to handle them via an abstraction layer like the List API does, it is its choice the read model doesn't care.

Also, as a small reminder, this needs to be donne with scalability in mind, most app are 90%/10% read/write or at least close to. I think we can remove that responsibility from the API since the problem is at the communication level like _at least once_ delivery. But maybe there is some work/thinking to be done and prep for things like serverless or multi-instances. Imo the readModel is a good candidate for this kinda of stuff.

I'm starting to dislike the terme API, i think we should refer to the terme adapter. Instead of exporting an object `module.exports = { fields, projections };` from a file in the readModel it could be `module.exports = ListAdapter({ fields, projections });`. Configuration for database connection could then be pass here or injected from the readModel (package.json).

**Comment by goloroden** [comment]
@jbeaudoin11 I agree that it probably would be a good idea to separate communications with the outer world (write model, clients, …) from the actual access to the database. This way, as you describe, it would be possible use a different adapter to access storage, but keep the read model the same. I like that idea 👍 

What I do not yet get right is how this separation could take place. If I only look at the communication with the outer world, we basically need to cover two things here:

- First we need to attach to the event bus so that we can react to incoming events.
- Second we need inform the client what has changed. We at least need the information here which table, list, graph, … has changed. What we do not necessarily need is the information what change exactly was taking place, but we need to know on the client-side which models need to be reloaded.

The first part is simple, and is done internally – as today. This means that when a developer defines a read model, she or he could write code to address a MongoDB. So, instead of the `projections` that you write today, you would write event handlers that use Mongoose, the MongoDB driver, or whatever suits your needs. Right? Actually, I can imagine this pretty easily.

And of course, we could provide you with predefined adapters here as well, so you do not *have* to write your own database code, but you could rely on wolkenkit as well, but you don't have to.

Now this brings up the question how to detect which lists have been updated. Would we simply say, it's the ones that have had an event handler for the event that just happened, and just assume that things have changed? Or …?

Do my summary and my thoughts roughly match what you had in mind? I have the feeling that you have some specific ideas, but I did not yet fully get them.

**Comment by goloroden** [comment]
@jbeaudoin11 Just a short update… 😊 

We're currently working in moving everything related to wolkenkit to a single repository, so that in the future we will have a monorepo approach. This should make things way easier for everyone.

As part of this transition, we are rethinking lots of things, and in this context we also came across this question again, and we're currently discussing how to solve this.

I don't have any specific news yet, but I just wanted to let you know that we are working on this, even if it's not visible yet on the surface 😉 

PS: If you want to have a look at the current state of the transition (which is heavily work in progress), see [this branch](https://github.com/thenativeweb/wolkenkit/tree/monorepo).

**Comment by goloroden** [comment]
For this we also have some pseudo-code. On the one hand, for the `package.json`:

```json
{
  "wolkenkit": {
    "eventstore": {
      "type": "postgres",
      "options": {
        // ...
      }
    },
    "viewstores": {
      "production-mongodb": {
        "type": "mongodb",
        "options": {
          // ...
        }
      },
      "my-experimental-elasticsearch": {
        "file": "/shared/viewstores/elasticsearch-experiments.js",
        "options": {
          // ...
        }
      }
    }
  }
}
```

On the other hand, for defining the views themselves:

```javascript
'use strict';

const store = {
  name: 'infrastructure/mongodb',

  async setup (peerGroups) {
    await peerGroups.ensureIndex('...');
  }
};

const projections = {
  'planning.peerGroup.joined': {
    handle (peerGroups, event) {
      peerGroups.insert(...);
    }
  }
};

const queries = {
  all: {
    schema: {
      where: {...},
      orderBy: {...}
    },

    handle (peerGroups, query, { client, logger }) {
      return peerGroups.find(...);
    }
  },

  top50Users: {
    handle (peerGroups) {
      return peerGroups.slice(0, 50);
    },

    isAuthorized (peerGroup) {
      // ...
    }
  }
};

module.exports = { store, projections, queries };
```

**Comment by goloroden** [comment]
wolkenkit v4 will introduce this model as the new read model, which provides way more flexibility. We're currently working on this. See [this sample application](https://github.com/thenativeweb/wolkenkit/tree/5349b1c19de79922bbdb11f46dab46d71e169f34/__temp__/sampleApplicationWithTypeScript) for what this will look like.
