### ISSUE TITLE
Wolkenkit becomes unresponsive 

### ISSUE THREAD

**Issue by timrach** [thenativeweb/wolkenkit#158]
### What is this bug about?
After some time, wolkenkit becomes unresponsive to new connections, commands and reads.  

### What steps are needed to reproduce the bug?
- In my application I upload 3 images per 'step' to the file storage and after the upload is finished, the storage ids are written to a container aggregate. 1 Container aggregate can have up to 400 steps i.e. 1200 images in the filestorage and 1200 ids stored in the container aggregate.
- The 3 images for 1 step are ~700kb in size in total 
- A step is generated every ~2 seconds
- The error occurs after approx. 1000 steps -> there should be about 3000 files in the file storage.

### What else should we know?
- Existing connections do not immediately timeout but only after a while.
- All docker containers are listed as 'UP'
- The computer did not go to sleep/hibernate during execution
- Logs can be accessed but don't show any error
- Trying to access wolkenkit via curl fails:

  ```
  curl https://local.wolkenkit.io:3001/v1/configuration.json --verbose
  *   Trying 127.0.0.1...
  * TCP_NODELAY set
  * Connected to local.wolkenkit.io (127.0.0.1) port 3001 (#0)
  * ALPN, offering h2
  * ALPN, offering http/1.1
  * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
  * successfully set certificate verify locations:
  *   CAfile: /etc/ssl/cert.pem
    CApath: none
  * TLSv1.2 (OUT), TLS handshake, Client hello (1):
  ```

  for comparison, on a healthy application instance `curl https://local.wolkenkit.io:3001/v1/configuration.json --verbose` shows:
  ````
  *   Trying 127.0.0.1...
  * TCP_NODELAY set
  * Connected to local.wolkenkit.io (127.0.0.1) port 3001 (#0)
  * ALPN, offering h2
  * ALPN, offering http/1.1
  * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
  * successfully set certificate verify locations:
  *   CAfile: /etc/ssl/cert.pem
    CApath: none
  * TLSv1.2 (OUT), TLS handshake, Client hello (1):
  * TLSv1.2 (IN), TLS handshake, Server hello (2):
  * TLSv1.2 (IN), TLS handshake, Certificate (11):
  * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
  * TLSv1.2 (IN), TLS handshake, Server finished (14):
  * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
  * TLSv1.2 (OUT), TLS change cipher, Client hello (1):
  * TLSv1.2 (OUT), TLS handshake, Finished (20):
  * TLSv1.2 (IN), TLS change cipher, Client hello (1):
  * TLSv1.2 (IN), TLS handshake, Finished (20):
  * SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
  * ALPN, server accepted to use h2
  * Server certificate:
  *  subject: OU=Domain Control Validated; OU=EssentialSSL; CN=local.wolkenkit.io
  *  start date: May 15 00:00:00 2017 GMT
  *  expire date: May 14 23:59:59 2020 GMT
  *  subjectAltName: host "local.wolkenkit.io" matched cert's "local.wolkenkit.io"
  *  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
  *  SSL certificate verify ok.
  * Using HTTP2, server supports multi-use
  * Connection state changed (HTTP/2 confirmed)
  * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
  * Using Stream ID: 1 (easy handle 0x7f867280b600)
  > GET /v1/configuration.json HTTP/2
  > Host: local.wolkenkit.io:3001
  > User-Agent: curl/7.54.0
  > Accept: */*
  >
  * Connection state changed (MAX_CONCURRENT_STREAMS updated)!
  < HTTP/2 404
  < server: nginx/1.14.2
  < date: Tue, 04 Jun 2019 09:32:15 GMT
  < content-type: text/html; charset=utf-8
  < content-length: 160
  < x-powered-by: Express
  < access-control-allow-origin: *
  < access-control-expose-headers: content-length,content-type,content-disposition,x-metadata
  < content-security-policy: default-src 'self'
  < x-content-type-options: nosniff
  <
  <!DOCTYPE html>
  <html lang="en">
  <head>
  <meta charset="utf-8">
  <title>Error</title>
  </head>
  <body>
  <pre>Cannot GET /v1/configuration.json</pre>
  </body>
  </html>
  * Connection #0 to host local.wolkenkit.io left intact
  ````

- `docker container stats`shows:
```
CONTAINER ID        NAME                   CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
bc4ede361e6d        helix-cloud-proxy      0.00%               2.43MiB / 1.952GiB    0.12%               1.89GB / 1.89GB     1.5MB / 4.1kB       2
4a0f9ea0d33f        helix-cloud-broker     0.34%               95.04MiB / 1.952GiB   4.75%               789MB / 771MB       7.46MB / 0B         12
56119b9c04f2        helix-cloud-flows      0.00%               57.56MiB / 1.952GiB   2.88%               2.4MB / 277kB       65.5kB / 0B         12
204f92df2cd7        helix-cloud-core       0.00%               76.55MiB / 1.952GiB   3.83%               140MB / 10.5MB      1.01MB / 0B         12
1ac5a4398c4a        helix-cloud-rabbitmq   0.79%               90.65MiB / 1.952GiB   4.54%               6.16MB / 6.48MB     14.8MB / 14.8MB     77
3b40522b9992        helix-cloud-postgres   0.00%               10.78MiB / 1.952GiB   0.54%               6.04MB / 138MB      8.61MB / 157MB      9
99681918ad29        helix-cloud-mongodb    0.55%               48.54MiB / 1.952GiB   2.43%               7.49MB / 887MB      21.6MB / 79.6MB     31
08365d380669        helix-cloud-depot      0.00%               52.66MiB / 1.952GiB   2.63%               723MB / 262MB       3.84MB / 0B         12

```

- After the error occurs I can't restart the application:
  `wolkenkit restart` is stuck forever at `Waiting for https://local.wolkenkit.io:3000/ to reply...`   
  ```
  wolkenkit stop
  wolkenkit start
  ``` 
  is also stuck forever at `Waiting for https://local.wolkenkit.io:3000/ to reply...`.

  To get the application back running, I have to stop the application, restart docker and start the application.

**Comment by goloroden** [comment]
Hey @timrach, thanks for bringing this issue up. You wrote:

> To get the application back running, I have to stop the application, restart docker and start the application.

What makes me wonder here is that you even have to restart *Docker*, not only the wolkenkit application, so I assume that this is rather a Docker problem of some kind (sockets exhausted, file handles exhausted, …) than a wolkenkit problem.

To better be able to reproduce your issue, can you please provide a minimal, but complete example, similar to what StackOverflow suggests when asking questions (see https://stackoverflow.com/help/minimal-reproducible-example for details)?

This would allow us to try to reproduce your actual case and see whether this also happens on one of our machines. Without this, there may be lots of aspects that influence this issue, so it's hard to track down by the bug report itself (nevertheless, this is very extensive and detailed, thanks for that!).

**Comment by timrach** [comment]
Hey @goloroden, I think your hunch about Docker being the culprit is right:
I prepared a minimal wolkenkit configuration and began to write a script mimicking the behaviour of the original application. While I was writing that script, the wolkenkit application was already running - and failing again after about 25 minutes, without being actually used. 
I then did a bit of research and of course I quickly found a lot of similar reports for docker desktop for mac (for example  https://github.com/docker/for-mac/issues/3674).
So...now I feel a bit stupid - but at least we can close this issue  😅

**Comment by goloroden** [comment]
@timrach No need to feel stupid – after all, you're the one who found the mistake 😊 

And to be honest, I'm somewhat glad to head that this is rather a Docker issue than a wolkenkit issue. 😅

**Comment by mattwagl** [comment]
@timrach No need to feel sorry at all. Thanks for taking the time and to get down to the details of this problem. Other people might run into this as well and it also confirms our current rewrite in order to get rid of docker for local development.
