### ISSUE TITLE
npm run start doesn't work on Windows after wolkenkit init

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#17]
As reported by @blumatixgs in #3 `npm run start` doesn't work after having run `wolkenkit init` on Windows 10.

@bluematixgs Is the following description correct, and can you please elaborate what *fails* means in the *Actual result* section?

### Steps to reproduce

- Setup wolkenkit according to the [documentation](https://docs.wolkenkit.io/latest/getting-started/installing-wolkenkit/installing-on-windows/)
- Run `wolkenkit init` in an empty directory
- Run `npm run start`

### Expected result

- The chat application starts.

### Actual result

- `npm run start` fails.

**Comment by goloroden** [comment]
I have an idea why it doesn't work… I had another look at [the line in `package.json`](https://github.com/thenativeweb/wolkenkit-template-chat/blob/9a574cdad6a727472b36b0dda88f2da8c06fc06f/package.json#L29) which is responsible for `npm run start`, and I guess that PowerShell does not understand the `&&` in this line.

@blumatixgs Can you (or anybody else) confirm that this does not work on PoSH? What is the equivalent of bash's `&&` in PoSH?

(The semantics is: Run the first command, then if the first was successful (and only then!), run the second.)

**Comment by goloroden** [comment]
PS: I think the easiest way to solve this is to get rid off the `npm run start` command and call those two steps manually.

**Comment by goloroden** [comment]
I [updated the documentation](https://github.com/thenativeweb/wolkenkit-template-chat/commit/9769c1a8623414d018abb6022e44b76cebfe0b24), so that it should now work on Windows as expected.

@blumatixgs Could you please have a look at this, and verify whether it works?

**Comment by blumatixgs** [comment]
@goloroden I can confirm that actual result of `npm run start` after `wolkenkit init` was fails on my office machine.

A view minutes ago I installed wolkenkit via Powershell on my private pc:

```
C:\WINDOWS\system32> docker-machine env --shell cmd wolkenkit
SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://10.0.0.17:2376
SET DOCKER_CERT_PATH=C:\Users\LocalUser\.docker\machine\machines\wolkenkit
SET DOCKER_MACHINE_NAME=wolkenkit
SET COMPOSE_CONVERT_WINDOWS_PATHS=true
REM Run this command to configure your shell:
REM     @FOR /f "tokens=*" %i IN ('"C:\Program Files\Docker\Docker\Resources\bin\docker-machine.exe" env --shell cmd wolkenkit') DO @%i
C:\WINDOWS\system32> [Environment]::SetEnvironmentVariable("DOCKER_TLS_VERIFY", "1", "User")
C:\WINDOWS\system32> [Environment]::SetEnvironmentVariable("DOCKER_HOST", " tcp://10.0.0.17:2376", "User")
C:\WINDOWS\system32> [Environment]::SetEnvironmentVariable("DOCKER_CERT_PATH", " C:\Users\LocalUser\.docker\machine\machines\wolkenkit ", "User")
C:\WINDOWS\system32>
```
Restarted PS with Admin rights then installed nodejs 6.11.4.

`npm install -g wolkenkit`

Reboot machine:

```
C:\tmp> cd .\demo\
C:\tmp\demo> dir
C:\tmp\demo> wolkenkit –version
  0.1.5
C:\tmp\demo> ping local.wolkenkit.io
Ping wird ausgeführt für local.wolkenkit.io [10.0.0.17] mit 32 Bytes Daten:
Antwort von 10.0.0.17: Bytes=32 Zeit<1ms TTL=64
Antwort von 10.0.0.17: Bytes=32 Zeit<1ms TTL=64
Antwort von 10.0.0.17: Bytes=32 Zeit<1ms TTL=64
Antwort von 10.0.0.17: Bytes=32 Zeit<1ms TTL=64
Ping-Statistik für 10.0.0.17:
    Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 0ms, Maximum = 0ms, Mittelwert = 0ms
```
Create demo project:

```
C:\tmp\demo> wolkenkit init
  Initializing a new application...
✓ Initialized a new application.
C:\tmp\demo>
C:\tmp\demo> npm run start
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Please include the following file with any support request:
npm ERR!     C:\tmp\demo\npm-debug.log
C:\tmp\demo>
```
This fails too. At work I remember that i called `npm install`. I did this also on this machine but the `node_modules` folder is empty and `wolkenkit start ` did not work either.
```
C:\tmp\demo2> wolkenkit start
  Starting the application...
  Failed to run Docker client.
✗ Failed to start the application.
```

**Comment by goloroden** [comment]
I'm very sorry, I should have been more explicit about the change: I have removed the `npm run start` command, hence it doesn't work any more (of course 😉).

This has been [updated in the documentation](https://github.com/thenativeweb/wolkenkit-template-chat#quick-start), so what you now need to do is to run `wolkenkit start` directly, but this fails again on your machine… hmmmmm 🤔

@grundhoeferj We will need to have another look at this.

**Comment by goloroden** [comment]
@blumatixgs Could you please retry starting the application, but this time using verbose mode, like this:

```shell
$ wolkenkit start --verbose
```

**Comment by goloroden** [comment]
@blumatixgs As in #18 you wrote:

> Perfect! Chat is running.

Is this issue still relevant?

**Comment by blumatixgs** [comment]
This issue can be closed. Thanks!

Von: Golo Roden [mailto:notifications@github.com]
Gesendet: Mittwoch, 25. Oktober 2017 07:52
An: thenativeweb/wolkenkit <wolkenkit@noreply.github.com>
Cc: Günter Schwaiger <g.schwaiger@blumatix-consulting.at>; Mention <mention@noreply.github.com>
Betreff: Re: [thenativeweb/wolkenkit] npm run start doesn't work on Windows after wolkenkit init (#17)


@blumatixgs<https://github.com/blumatixgs> As in #18<https://github.com/thenativeweb/wolkenkit/issues/18> you wrote:

Perfect! Chat is running.

Is this issue still relevant?

**Comment by goloroden** [comment]
Great, thanks a lot for your quick reply 😊
