### ISSUE TITLE
Application is running, but not reachable after reboot on Windows 10

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#18]
As reported by @blumatixgs in #3 there is an issue with running wolkenkit applications after a machine reboot on Windows 10.

@blumatixgs Could you please have a look at this issue, and elaborate on what exactly *not reachable* means? What *exactly* happens when you try to reach the application?

### Steps to reproduce

- Run a wolkenkit application on Windows 10
- Verify that it works and that it is reachable
- Reboot the machine

### Expected result

The wolkenkit application is running and reachable.

### Actual result

The wolkenkit application is running, but not reachable.

**Comment by goloroden** [comment]
@blumatixgs Is it possible that the *backend* is still running, but not the *frontend*? In other words: Does https://local.wolkenkit.io/v1/ping return a result? If so, then the backend is definitely running.

The frontend doesn't survive restarts (but this is by design, as wolkenkit only cares about the backend), so you need to re-run `http-server` after a reboot.

Does this solve the problem?

**Comment by blumatixgs** [comment]
@goloroden What is the correct command to start the `http-server` only?
In the updated documentation you wrote `npx http-server ./client/ -o`. This should be `npm http-server ./client/ -o`?

You also removed the `devDependency` in the package.json - that is the reason why `npm install `does nothing.
```
  "devDependencies": {
    "http-server": "0.10.0"
  },

```
If I add the dependency again in the package.json file and installed it the `npm http-server ./client/ -o` command fails with this error message:

```
C:\tmp\demo4>npm http-server ./client/ -o

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Günter\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.10 C:\Program Files\nodejs\node_modules\npm
```

**Comment by goloroden** [comment]
Thanks for the fast reply 😊 

I actually meant `npx`, but as I have seen this is only available from npm 5.x on. Since you are using Node 6.x, you can't use `npx`.

Then you need to do the following: Install the `http-server` globally by running

```shell
$ npm install -g http-server
```

and then run the frontend:

```shell
$ http-server ./client/ -o
```

The installation, of course, needs to be done only once.

PS: I'm going to update the docs accordingly.

**Comment by goloroden** [comment]
PPS: Done, the [documentation is updated](https://github.com/thenativeweb/wolkenkit-template-chat/blob/master/README.md#quick-start).

**Comment by blumatixgs** [comment]
@goloroden Perfect! Chat is running.

**Comment by goloroden** [comment]
Yay 🎉 

Then I'm going to close this issue. Thanks for your help 😊
