### ISSUE TITLE
Replace MongoDB in samples applications by PostgreSQL

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#1805]
### What is this task about?

Right now, in the sample applications we use a MongoDB for queries, but we don't start a MongoDB in the scripts. To avoid having to set up two databases for the samples, it would make sense to update the sample applications to use PostgreSQL for querying as well.

### What needs to be done to complete this task?

- [x] Setup the required tables
- [x] Update the sample applications' code
- [ ] Test the sample applications

**Comment by yeldiRium** [comment]
We have decided not to go through with this. Instead, we will go with #1811 and stick to MongoDB in the sample applications.
