### ISSUE TITLE
Missing Readme

### ISSUE THREAD

**Issue by paulito-bandito** [thenativeweb/wolkenkit#1852]
### What is this bug about?
Hi all, it's probably on purpose, but I'd like to run this project, not the 4.0 preview so it's a mystery how to run this project.
…

### What is the expected result?
That I could see the Readme for this project.
…

### What is the actual result?
I see the readme for preview of 4.0
…

### What steps are needed to reproduce the bug?
I open this url: https://github.com/thenativeweb/wolkenkit/issues/new?assignees=&labels=&template=bug.md
- …
- …
- …

### What else should we know?
This is probably by design, but it's a shame bc this repository looks quite good. 
…

**Comment by goloroden** [comment]
For the previous version‘s documentation, see https://docs.wolkenkit.io/3.1.0/

However, I would not recommend to do this, since work on 4.0 is almost finished (actually, almost the only thing missing right now is the final documentation).
