### ISSUE TITLE
Ensure that the priority queue runs stable

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#1898]
### What is this task about?

From time to time, we have the problem that the priority queue does not behave stable. This sometimes makes the tests fail, but we do not yet know why. We have to figure out what the problem here is.

### What needs to be done to complete this task?

- [ ] Figure out whether this affects all implementations, or just some of them
- [ ] Find the root cause of the error (this probably should be done together with @strangedev and @dotKuro)
- [ ] Fix it

**Comment by strangedev** [comment]
We built some fuzzing tests for our various priority queue implementations and simulated load for about 2 hours on each implementation (#1935). We didn't find anything related to this issue, so we're closing this for the time being, until we get further reports which we can investigate.
