### ISSUE TITLE
Fix warnings in tests

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#1900]
### What is this task about?

When running the tests, there are two warnings that are reported a few times, i.e.

> Top-level use of w, wtimeout, j, and fsync is deprecated. Use writeConcern instead.

and:

> Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency

Both seem to be related to the MongoDB driver. We should have a look at where they come from and fix them.

### What needs to be done to complete this task?

- [x] Find the cause for these warnings
- [ ] Fix them
- [ ] Verify that there are no other warnings in test execution

**Comment by goloroden** [comment]
Regarding first problem (with `writeConcern`), the types of `@types/mongodb` do not reflect the current state of the driver API, see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/51191

Until now, I didn't have the time to dive into the second one, so no info on that (except that according to the types package the `MongoError` class should be there … I guess, similar problem).

**Comment by strangedev** [comment]
Regarding the second warning, there is a fix that was pulled into the 3.6 branch of MongoDB not long ago: https://github.com/mongodb/node-mongodb-native/commit/d67ffa7a2e3f86734c7e9b6944aab1d765b9e75e

We will probably see this released in the next 3.6.x version, which would be 3.6.5.

**Comment by yeldiRium** [comment]
3.6.5 was released.
