### ISSUE TITLE
The client generated by init does not use the current API routes.

### ISSUE THREAD

**Issue by strangedev** [thenativeweb/wolkenkit#1941]
### What is this bug about?

When we bootstrap the chat demo application by `npx wolkenkit@4.0.0-internal.108 init`, the client uses old API routes, causing a 404 error.

### What is the expected result?

When we bootstrap the chat demo application, it works as-is.

### What is the actual result?

The chat demo application is not usable, since the client can't fetch from the back-end.

### What steps are needed to reproduce the bug?

- `npx wolkenkit@4.0.0-internal.108 init`
- `npm install`
- `npx wolkenkit dev`
- `cd client && npx http-server`

### What else should we know?

In some internal release, we started differentiating between streaming APIs and APIs that just return a value. Adding `/stream` or `/value` to the paths fixes the issue.

**Comment by manassikri** [comment]
Hey.
Is this bug still open? I would like to work on this.

**Comment by goloroden** [comment]
Hey 👋 

Yes, this is still open, and thanks for your offer to help 😊 

I think we already have a PR open for that (see #2651).
Unfortunately, we did not yet have time to review it.

But maybe you want to take a closer look at it?

**Comment by goloroden** [comment]
Hey @manassikri 👋 

Thanks for offering help 😊 

We actually already have a PR for that (see #2651), however it wasn't reviewed until now, but I just had a look at it, and I am going to merge it soon 😊 

So, thanks again for offering your help!
