### ISSUE TITLE
Wolkenkit restart not working when wolken kit is stopped

### ISSUE THREAD

**Issue by MuwuM** [thenativeweb/wolkenkit#2]
When I try to execute the restart command and wolkenkit app is not running I get an error message that my app is not running and it is not starting. From similar commands of other CLIs I would expect it to start anyway.

```
wolkenkitdev@wolkenkitdev ~/jsdoc/chat $ wolkenkit restart
✗ chat is not running.

```

**Comment by goloroden** [comment]
Thanks for bringing this issue up.

We will address this in a future release, when we are going to rework some parts of the CLI anyway.

**Comment by goloroden** [comment]
To show a sign of life… we are currently in the process of rewriting the CLI from scratch. As part of this we will take this issue into account.

As soon as there are some news on this (and something to play around with), we will let you know 😊

**Comment by goloroden** [comment]
@MuwuM We now have implemented this behavior in the new version of the CLI, and it will be publicly available soon 😊 

Hence I'm going to close this issue now.
