### ISSUE TITLE
Introduce categories for UX components

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#200]
### What is this feature about?

Currently, the UX components are all at top-level, but it would probably be reasonable to sort them into categories. This way the list would be shorter, and navigating the controls would be easier. @mattwagl and I thought about how to sort things, and this issue is the result of this.

### What needs to be done to implement this feature?

- [x] Introduce the following categories
  - [x] `roots`
    - [x] `Application`
    - [x] `ApplicationServices`
      - [x] Clarify with @mattwagl whether they are actually still needed
    - [x] `StyleCollector`
    - [x] `ThemeProvider`
    - [x] `Website`
  - [x] `layout`
    - [x] `Container`
    - [x] `Grid`
    - [x] `GridItem`
    - [x] `Sidebar`
    - [x] `SidebarBrand`
    - [x] `SidebarItem`
    - [x] `SidebarFooter`
    - [x] ~~`View`~~
  - [x] `branding`
    - [x] `Brand`
    - [x] `MadeBy`
    - [x] `Pattern`
    - [x] `PoweredBy`
    - [x] `Product`
  - [x] `typography`
    - [x] `Headline`
    - [x] `Label`
    - [x] `Text`
  - [x] `graphics`
    - [x] `Icons`
    - [x] `Icon`
    - [x] `LogoFull`
    - [x] `LogoMinimal`
    - [x] `LogoTheNativeWeb`
    - [x] `LogoWolkenkit`
  - [x] `input`
    - [x] `Button`
    - [x] `ButtonHint`
    - [x] `CheckBox`
    - [x] `Dropdown`
    - [x] `Link`
    - [x] `TextArea`
    - [x] `TextBox`
    - [x] `Toggle`
  - [x] `forms`
    - [x] `ControlGroup`
    - [x] `ControlGroupDivider`
    - [x] `ControlGroupItem`
    - [x] `Form`
    - [x] `FormActions`
    - [x] `FormRow`
  - [x] `feedback`
    - [x] `BusyIndicator`
    - [x] `Dialogs`
    - [x] `Message`
    - [x] `Modal`
    - [x] `ModalRow`
    - [x] `Notification`
  - [x] `animation`
    - [x] `Transition`
    - [x] `TransitionGroup`
- [x] Update the test structure
  - [x] unit
  - [x] integration
    - [x] Adjust colors in container tests to tnw like colors
    - [x] ~~Move `website.tsx` and `components.tsx` pages to new structure~~ (This will be done in a new branch that introduces our new styleguide ideas since this will touch these files anyway)
  - [x] ~~Add new test type for styleguide~~ (We removed styleguidist. We can simply do this using integration tests) 
- [x] Update all modules to named exports

### What else should we know?

The documentation needs to be cleaned up as well, but this is outside the scope of this issue.

**Comment by mattwagl** [comment]
We made it! Thanks @vaalllaa and @goloroden for this team effort. 🎉
