### ISSUE TITLE
Highlight menu item on scroll in UX styleguide

### ISSUE THREAD

**Issue by vaalllaa** [thenativeweb/wolkenkit#229]
### What is this feature about?

Currently the users have two ways to switch to a certain topic. First by clicking a menu item in the sidebar and second by scrolling in the content itself on the right side.

If the users choose to click on the menu item, it get's highlighted and the content scrolls to this chosen topic. But if the users choose to navigate on the content side and switches topics by scrolling, the sidebar menu doesn't follow the users with highlighting the focused topic.
…

### What needs to be done to implement this feature?

- [ ] Implement menu-item highlighting in relation to content scrolling

**Comment by mattwagl** [comment]
Going to close this since we're moving away from the current styleguide solution. The new styleguide won't be a one pager anymore. If similar problems arise within the "new" solution, we can open a new issue.
