### ISSUE TITLE
Cannot start a Wolkenkit application on Windows

### ISSUE THREAD

**Issue by colorizedmind** [thenativeweb/wolkenkit#26]
I set up Wolkenkit 1.2.0 on Windows 10 Professional as described in the [documentation](https://docs.wolkenkit.io/1.2.0/getting-started/installing-wolkenkit/installing-on-windows/). When I run `wolkenkit start` there's an error:

```
$ wolkenkit start
  Starting the application...
  Verifying health on environment default...
⠙events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
```

The same error occurs when I'm trying to start a Wolkenkit template or when I'm using the `wolkenkit health` command. The Hyper-V machine is up and running and responds to pings.

### Steps to reproduce

* Install Wolkenkit on a Windows machine
* Initialize a new application with `wolkenkit init`
* Start the application `wolkenkit start`

### Expected result

* The application starts.

### Actual result

* The application doesn't start and an error is shown.

**Comment by goloroden** [comment]
Can you please re-run the start command, but this time using the —verbose flag, and provide the output? This may help us to track down the root cause.

**Comment by grundhoeferj** [comment]
Hey @colorizedmind 😊 

i will start my windows VM and take a closer look at this topic. As mentioned before the output with `--verbose` would be great 👍

**Comment by grundhoeferj** [comment]
Hey @colorizedmind 😊 

we have released a new version of the CLI, which fixed your mentioned bug.
Please upgrade to version 1.2.1 with the following command: `npm install -g wolkenkit`

Can you give us feedback, if it works on your machine?

**Comment by goloroden** [comment]
PS: @colorizedmind If you have any further questions we would like to welcome you in our [wolkenkit Slack team](http://slackin.wolkenkit.io) 😊

**Comment by colorizedmind** [comment]
It works on my machine. Thanks!
