### ISSUE TITLE
React integration?

### ISSUE THREAD

**Issue by pyros2097** [thenativeweb/wolkenkit#27]
How could we integrate wolkenkit to a react based app? An example would be nice.

**Comment by goloroden** [comment]
There are a number of [sample applications](https://github.com/thenativeweb/wolkenkit#sample-applications) available, some of them use React.

As an easy to grasp example you might start with [wolkenkit-nevercompletedgame](https://github.com/thenativeweb/wolkenkit-nevercompletedgame).

There you can see how to connect, how to send commands, handle events, and run queries.
