### ISSUE TITLE
not working "wolenkit start" command on ubuntu 16

### ISSUE THREAD

**Issue by chagamkamalakar** [thenativeweb/wolkenkit#31]
![image](https://user-images.githubusercontent.com/6966631/35752655-b49e2cca-0882-11e8-88bc-56f32c2a3015.png)

any help please

**Comment by goloroden** [comment]
Hey 😊

Thanks for bringing up this issue!

Apparently the CLI is not able to communicate with your Docker, so we need to figure out why. 

Can you please re-run the start command, using the —verbose flag?

**Comment by chagamkamalakar** [comment]
thank  you

after running  `wolkenkit start --verbose`

i could see same error messages 

![image](https://user-images.githubusercontent.com/6966631/35763135-887fbfca-08cb-11e8-88f7-778d2eeea611.png)

**Comment by goloroden** [comment]
Hmmm, okay. 

Does directly running a Docker command work? How is Docker configured?

**Comment by chagamkamalakar** [comment]
I follow the instructions @   https://docs.docker.com/install/linux/ubuntu/

`sudo docker run hello-world` worked properly. 

![image](https://user-images.githubusercontent.com/6966631/35765635-2a706d26-08ee-11e8-8848-63fbb2899269.png)

**Comment by goloroden** [comment]
Does it work without `sudo` as well?

**Comment by chagamkamalakar** [comment]
not working

![image](https://user-images.githubusercontent.com/6966631/35766122-c9be7c3e-08f7-11e8-93f0-61d9734d5b3f.png)

**Comment by goloroden** [comment]
As said, then this is the cause of the problem. wolkenkit assumes that you can run `docker` as normal user. See the [post-installation steps for Linux](https://docs.docker.com/install/linux/linux-postinstall/) to address this problem.

Once you can run `docker` without `sudo`, wolkenkit should work as well.

**Comment by chagamkamalakar** [comment]
thank you ... it's working now

**Comment by goloroden** [comment]
Great 😊

**Comment by chagamkamalakar** [comment]
@goloroden  is there any specific reason to build this on docker .. why can't it be on base machine

**Comment by goloroden** [comment]
This is because wolkenkit is a distributed application, which builds on several processes, and it requires RabbitMQ, PostgreSQL and MongoDB to be setup correctly.

Using Docker allows us to setup everything for you (except Docker), which makes development (and especially getting started) way faster and easier, than if you had to setup everything on your own.

Of course there are downsides as well, but so far our impression was the the advantages outweigh the disadvantages.

**Comment by chagamkamalakar** [comment]
thank you for this clear explanation.
i found it difficult as i never experienced docker.

**Comment by goloroden** [comment]
You're welcome 😊 

I understand that, and I agree with you that if one has never worked with Docker, it is not _that_ easy to get started. Fortunately (for us), Docker gets more and more widespread used, but yes, the hurdle to get started could be lower…

I hope that time will help here 😉

**Comment by chagamkamalakar** [comment]
but after going through first article @ https://auth0.com/blog/building-real-time-web-applications-using-wolkenkit/

i found it interesting to work on. 

we are right now  wokking on tourism related b2b software  using laravel 5.4 & vuejs 2.

 does it have good authorization features?

**Comment by chagamkamalakar** [comment]
thank you.

**Comment by goloroden** [comment]
You're welcome 😊
