### ISSUE TITLE
Distribute commands over multiple domain servers

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#339]
### What is this feature about?

In the past, commands were only handled by a single domain server (back then, it was called the `core`). It would be great to be able to distribute commands over multiple domain servers, to be able to scale and to load-balance. However, one must pay attention to the fact that no two commands for the same aggregate may be run at the same time.

We will have the following routes:

- `GET /` is a route that stays open until a result is available, which means it needs to send a ping from time to time to keep the connection open. Once a command could be locked successfully, this route returns this command and gets closed by the server.
- `POST /renew-lock` renews a lock, and the required data is sent in the body as JSON.
- `POST /acknowledge` acknowledges a lock, and the required data is sent in the body as JSON.

### What needs to be done to implement this feature?

- [x] Implement an in-memory priority queue
  - [x] Add unit tests
  - [x] Use `contextIdentifier`, `aggregateIdentifier`, `id` and `name` as parameters for `renewLock` and `acknowledge`
- [x] Design a `awaitCommandWithMetadata` API
- [x] Implement the `awaitCommandWithMetadata` API
  - [x] Extract a `streamNdjsonMiddleware` (or something similar`) from the domain events API, which takes care of the heartbeat, the headers, and so on, and reuse it
  - [x] Add unit tests
- [x] Build a server for the `microservices` runtime
  - [x] Use the `handleCommandWithMetadata` API
  - [x] Use the `awaitCommandWithMetadata` API
  - [x] Add runtime tests

**Comment by yeldiRium** [comment]
Done :)
