### ISSUE TITLE
How to clear entries from the database and recreate the denormalised data

### ISSUE THREAD

**Issue by sscholle** [thenativeweb/wolkenkit#34]
Please help me with clearing the database from old, erroneous data.

I'm guessing there are access credentials needed to 'clear' the Events

How about the denormalised data, thats stored in mongo?

What process should i follow to for example, remove old test data?

**Comment by goloroden** [comment]
If you restart (instead of reload) your application, the databases are cleared. For more details see https://docs.wolkenkit.io/1.2.0/reference/using-the-cli/controlling-the-lifecycle/#restarting-an-application
