### ISSUE TITLE
Mark domain events as GDPR relevant

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#340]
### What is this feature about?

When storing domain events in the event store, some of them contain person-related data, such as names, addresses, and so on. These data may need to be anonymized, pseudonymized, or even deleted. To be able to differ which domain events are affected and which aren't, we need a way to tell them apart. This means that for each event we save, we need to save an additional marker that tells whether the domain event contains potentially problematic data or not.

### What needs to be done to implement this feature?

- [ ] Introduce a new field to all event store implementations to mark events as relevant for GDPR
- [ ] Add a new parameter `containsPersonalData` (or something similar) to the `saveDomainEvents` function and use `true` as default
- [ ] Add and adjust tests

**Comment by goloroden** [comment]
Just an idea… it may make sense to *not* implement something specific for GDPR and / or personal data, but to introduce the option to add tags to events, e.g. to categorize them. This way you could easily setup your own topology, which you might _also_ use for managing GDPR-related events, but you could use them for lots of other things as well.

Before this is going to be implemented, we should discuss this once again.

**Comment by yeldiRium** [comment]
We decided on implementing this via tags, which will be more generic. Thus I'm closing this issue.
