### ISSUE TITLE
Provide a test runner for wolkenkit applications

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#344]
### What is this feature about?

Right now it is pretty hard to test wolkenkit applications (which also means it is hard to test wolkenkit as an entire system). We should come up with a test runner based on Cucumber.js to test wolkenkit applications, similar to the following form:

```
Given an aggregate of type 'SampleAggregate'
  And a domain event of type 'executed' with payload '{ "strategy": "succeed" }'
When I send a command of type 'execute' with payload '...'
Then an event of type 'executeFailed' should be published
```

### What needs to be done to implement this feature?

- [ ] Define the scope of what to test
- [ ] Define specific steps
- [ ] Implement these steps as a library
- [ ] Setup tests for a sample application
- [ ] Think about how to test the steps and the test runner

### What else should we know?

This solves #119. Since this was brought up by @gossi we should notify him once this has been implemented.

**Comment by gossi** [comment]
Cool. Love to see that gherkin for acceptance tests. Since ember provides me the test runner out of the box, I have to ask: Do you plan on providing a testing environment for unit and integration tests, too?

**Comment by goloroden** [comment]
@gossi We do not yet have specific plans or a concept for this, but I'd say that we will have to do a lot of things to enable testing support (this is one of the areas where v3 does not provide anything, although this is super-important). So, without being able to promise anything, I'd say that for v4 we will take care of this in a way better way. What this exactly means for unit and / or integration testing needs to be seen, but as said… we want to improve things dramatically here 😊

**Comment by goloroden** [comment]
Superseded by #870, and hence closed.
