### ISSUE TITLE
Support transactions in MongoDB

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#362]
### What is this feature about?

So far, we marked MongoDB support as experimental in the [wolkenkit-eventstore](https://github.com/thenativeweb/wolkenkit-eventstore) module. The reason for this is that MongoDB did not support transactions in the past, which are needed to guarantee an all-or-nothing semantics when saving multiple events. MongoDB 4.0 introduced transaction support, and we should add support for them to wolkenkit.

### What needs to be done to implement this feature?

- [x] Figure out how MongoDB transactions work
- [x] Update all MongoDB-based adapters
- [x] Adjust tests, if necessary

**Comment by quarterpi** [comment]
Would this allow for replica sets and sharding? Or is it a single MongoDB server?

**Comment by goloroden** [comment]
Basically, this shouldn't make a difference regarding replica sets / sharding or a single server, since with wolkenkit v4 you will be able to configure the connection string on your own. If you provide a connection string that points to a cluster, wolkenkit will work with a clustered MongoDB. If you provide a connection string pointing to a single server, this will work, too.

**Comment by quarterpi** [comment]
Fantastic, thank you 🙂
