### ISSUE TITLE
Implement a push  mechanism for the priority queue

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#369]
### What is this feature about?

Right now we need to pull the priority queue for new items, if there is currently no work to be done. This leads to unneeded CPU usage, and – once we have the dispatcher backed with a database – to unnecessary network traffic. We should change this to a push-based mechanism, to avoid both effects. If we had a push, then it would be the `enqueue` function's job to emit an event, and the job of all waiting receivers to subscribe to these events. For performance reasons, it may be a good idea to throttle the events.

### What needs to be done to implement this feature?

- [x] Define an interface `lib/messaging/pubSub/PubSub`
- [x] Build an event-emitter compatible in-memory implementation
- [x] Add tests
- [x] Integrate pub sub service into dispatcher process
  - [x] Remove `QUEUE_POLL_INTERVAL` configuration option

**Comment by yeldiRium** [comment]
Done :)
