### ISSUE TITLE
The client SDK uses an old lodash version

### ISSUE THREAD

**Issue by quarterpi** [thenativeweb/wolkenkit#437]
I get an alert that 2 packages have high severity vulnerabilities:

> lodash < 17.4.12 vulnerable to prototype polution

Blame wolkenkit-client->lodash. Fixed in >= 17.4.12.

Can we bump the pinned version to fix this?

**Comment by goloroden** [comment]
As already mentioned in https://github.com/thenativeweb/wolkenkit-client-js/pull/11 this unfortunately is not as easy as it seems to be 😢 

Hence we will probably not be able to do this in an easy and quick way.

With v4 the release process gets dramatically easier, and then we will be able to push such updates out very easily, but I fear that for now we will have to live with it 😢

I'm sorry that I don't have a better answer right now.
