### ISSUE TITLE
wolkenkit start fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by czosel** [thenativeweb/wolkenkit#5]
After setting up a new project with `wolkenkit init` on my Ubuntu 16.04 machine, `wolkenkit start` fails with the message
`✗ Failed to create container chat-broker. Error response from daemon: invalid IP address in add-host: ""`
I'm running docker v17.05.0-ce.

Any help is much appreciated!

**Comment by goloroden** [comment]
Thanks for bringing up this issue 😊 

This seems to be a problem with the latest Docker versions.

If you setup a VM, e.g. using `docker-machine`, with 17.03 everything works as expected. We are investigating this issue, and will let you know once it has been fixed.

**Comment by goloroden** [comment]
PS: We have also [reported this issue](https://github.com/moby/moby/issues/33912) to the people from Docker, so it may be worth watching that thread as well.

**Comment by goloroden** [comment]
Great news: We have found the issue and will release a new version of the CLI shortly…

**Comment by czosel** [comment]
:+1: awesome, thank you!

**Comment by goloroden** [comment]
@czosel Could you please run:

```bash
$ wolkenkit update
$ wolkenkit --version
```

This should tell you that you are on `1.0.2`.

If you then try to re-run `wolkenkit start` again - is the error gone?

**Comment by czosel** [comment]
Yes, it's working now :smiley: Thanks again for the prompt response!

**Comment by goloroden** [comment]
You're welcome 😊 

Then, I'm closing this issue.
