### ISSUE TITLE
[FEATURE REQUEST]: Allow for other auth mechanisms

### ISSUE THREAD

**Issue by go4cas** [thenativeweb/wolkenkit#51]
At present, wolkenkit only supports OpenID Connect for auth. There will be cases where this might not be feasible/relevant, e.g. existing authentication/authorization microservices, etc.

**Comment by goloroden** [comment]
You are right, that right now the only supported authentication schema is OpenID Connect. However, the system has been built in a way that this can be changed by using plugins.

For the existing plugins, see here: https://github.com/thenativeweb/wolkenkit-client-js/tree/master/src/authentication

If you need anything above that, we can discuss this in Slack, and maybe you can come up with a PR.
