### ISSUE TITLE
Fix the race condition in the lock store

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#519]
### What is this task about?

In the lock store, when acquiring a lock, we have a race condition: First we check whether there is already an (expired) lock, and if so, we update it, otherwise we insert a new one (see [this example](https://github.com/thenativeweb/wolkenkit/blob/0eb4ca501763ff4974351d02ab76ddc3dc1db09d/lib/stores/lockStore/MariaDb/MariaDbLockStore.ts#L133-L174) from the MariaDB lock store). However, if a lock exists, but another client concurrently releases the lock, it gets deleted, so it can't be updated any more.

We could fix this by first trying to delete all expired locks, and then always inserting. Either inserting works, or it doesn't. Another option may be to use some kind of upsert, but this sounds more complicated. Either way, we need to fix this.

### What needs to be done to complete this task?

- [x] Decide how to fix the race condition
- [x] Fix the race condition in all providers

**Comment by yeldiRium** [comment]
I've decided to fix the race condition by first deleting all expired locks and then trying to insert a new one. If someone else got the lock first, inserting will fail and the appropriate error will be thrown.
