### ISSUE TITLE
Roadmap site/doc

### ISSUE THREAD

**Issue by go4cas** [thenativeweb/wolkenkit#52]
Would it be possible to publish the wolkenkit roadmap and/or feature release dates?

**Comment by goloroden** [comment]
We have a roadmap online, see here: https://github.com/thenativeweb/wolkenkit/blob/master/roadmap.md

It is very high-level, but actually the only thing close to a roadmap we currently have. Regarding release dates, we don't have them. Features are done when they are done.

Sorry that I have no better answer here for you.

**Comment by goloroden** [comment]
PS: If you are interested in a specific feature, let's discuss this on Slack.
