### ISSUE TITLE
Real-world Example

### ISSUE THREAD

**Issue by go4cas** [thenativeweb/wolkenkit#53]
The current example code is for very basic use cases. It would be great if you could include a more real-world example, with more complex entities, etc.

**Comment by goloroden** [comment]
I perfectly understand your need for a more complex application, and I can tell you that we will release more complex ones in the future.

One of our customers is currently building a solution for a real-world scenario, and this application will be open-sourced once it goes live (which should either be in Q4/2018 or Q1/2019).

Right now we focus on preparing the next release of wolkenkit, so unfortunately we don't have the resources (right now) to come up with another, more complex application. But as said, it will happen eventually.
