### ISSUE TITLE
Cannot run demo application on Ubuntu 18.04

### ISSUE THREAD

**Issue by CarstenWalther** [thenativeweb/wolkenkit#54]
### What is this bug about?
I am setting up wolkenkit and going through the tutorial.
I cannot start the demo application.

### What steps are needed to reproduce the bug?
Don't know if it's reproducible but I'm going through the tutorial:
- Fresh node and docker setup (also did the Docker post-install steps)
- Fresh wolkenkit installation
- `wolkenkit init`
- `wolkenkit start`

The application stops at `Building Docker images...`.
I got docker images but no containers.

### What is the expected result?
The demo application starts without issues.

### What is the actual result?
This is the output if I run `wolkenkit start --verbose`

```
  Starting the application...
  Verifying health on environment default...
  Application host local.wolkenkit.io resolves to 127.0.0.1.
  Docker server resolves to 127.0.0.1 and ::1.
  Verifying application status...
  Verifying that ports are available...
  Setting up network...
  Building Docker images...
✗ Failed to start the application.
  unable to prepare context: path "/tmp/p1RZVL" not found

  ExecutableFailed: unable to prepare context: path "/tmp/p1RZVL" not found

    at new CustomError (/home/cwalther/.nvm/versions/node/v10.12.0/lib/node_modules/wolkenkit/node_modules/defekt/dist/defekt.js:44:116)
    at /home/cwalther/.nvm/versions/node/v10.12.0/lib/node_modules/wolkenkit/dist/shell/exec.js:29:18
    at ChildProcess.exithandler (child_process.js:296:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)

```

### What else should we know?

I am using:
* Ubuntu 18.04.1
* Node 10.12
*  Docker 18.06.1-ce

**Comment by CarstenWalther** [comment]
Get the same error with Node v8.11.3

**Comment by goloroden** [comment]
Hi @CarstenWalther 😊 

Thanks for bringing up this issue!

Actually, it seems to be a problem related to Docker, not to wolkenkit. If you search the web for `unable to prepare context` you find lots of Docker issues, where people get this error in one form or another.

If you try to build a Docker image manually, does this work?
And can you start containers manually?

**Comment by CarstenWalther** [comment]
Hi @goloroden,
thanks for the fast response!

I can pull the following images without an error:
```
thenativeweb/wolkenkit-flows:2.0.0
thenativeweb/wolkenkit-depot-file:2.0.0
thenativeweb/wolkenkit-core:2.0.0
thenativeweb/wolkenkit-broker:2.0.0
thenativeweb/wolkenkit-postgres:2.0.0
thenativeweb/wolkenkit-rabbitmq:2.0.0
thenativeweb/wolkenkit-node-modules:2.0.0
thenativeweb/wolkenkit-mongodb:2.0.0
```
I guess a command similar to this causes the error:
```
> ls /tmp/jthykP/
Dockerfile  package.json  server
> docker build -t test:latest /tmp/jthykP
unable to prepare context: path "/tmp/jthykP" not found
``` 
Using the full path to the Dockerfile still does not work:
```
> docker build -t test:latest /tmp/jthykP/Dockerfile
unable to prepare context: path "/tmp/jthykP/Dockerfile" not found
```
If I go into the directory and try to build the image, I get this strange error:
```
> docker image build -t test:latest .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /var/lib/snapd/void/Dockerfile: no such file or directory
```
I don't know from where it gets this path.

**Comment by goloroden** [comment]
Did you install Docker using Snap?

**Comment by CarstenWalther** [comment]
yes

**Comment by goloroden** [comment]
There seems to be a problem with Docker installed using Snap which causes this error. If you do follow the installation instructions given in the Docker documentation, things should work.

**Comment by CarstenWalther** [comment]
Thanks. I will try it with docker from their apt repository next week.

**Comment by goloroden** [comment]
Sorry for the trouble 😔

Could you maybe report back if it worked?

**Comment by CarstenWalther** [comment]
Sure, I'll do.

**Comment by goloroden** [comment]
PS: Not directly a solution for your problem, but apparently others have the [exact same problem](https://stackoverflow.com/questions/51746266/problems-with-building-image-using-snap-docker) as well when installing Docker via Snap.

According to the comments and the answer there, installing Docker via `apt-get` instead of Snap helped.

**Comment by CarstenWalther** [comment]
It does work with docker from the apt repository.

**Comment by goloroden** [comment]
That's great news, so I'm going to close this 😊

**Comment by Hi-Angel** [comment]
Breaking news, folks! It turns out, somebody just [notified the actual package maintainers](https://github.com/docker-snap/docker-snap/issues/34) of this packaging bug, so we can hope it will be resolved!
