### ISSUE TITLE
Setup base documentation application

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#543]
### What is this feature about?

Historically, the documentation of wolkenkit was in a separate repository. In the future we should have the documentation alongside with the code, in a single repository. So we need to setup a base application to run the documentation.

### What needs to be done to implement this feature?

- [x] Setup a Next.js based application
  - [x] Setup the base application layout
  - [x] Extract Hint component from legacy branch
  - [x] Setup a static build export
  - [x] Create a concept for i18n (and upgrade Navigation component from ux module)
- [ ] ~~Integrate with other versions online~~
- [x] Introduce a `documentation` command to the CLI
- [x] Provide the documentation on Netlify
- [x] Add tests for the CLI `documentation` command

**Comment by mattwagl** [comment]
Work has begun under the new [next-documentation](https://github.com/thenativeweb/wolkenkit/tree/next-documentation) branch. For now we're keeping the old branch as [next-documentation-legacy](https://github.com/thenativeweb/wolkenkit/tree/next-documentation-legacy).
