### ISSUE TITLE
Provide a simple proxy for the microservice runtime

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#545]
### What is this feature about?

The microservice API provides different processes for the command and the domain event API, so they do run on – at least – different ports. It would be great to have a unified entry point, i.e. a proxy in front of them. We need to figure out how to do this. However, this proxy should only be very basic, since this task is in the end up to the person running the infrastructure for a wolkenkit application.

### What needs to be done to implement this feature?

- [x] Evaluate various proxies, such as NGinx, HAProxy, træfik, …
- [x] Figure out how to pass through and combine HTTP
- [ ] Figure out how to pass through and combine GraphQL
- [ ] Add tests

**Comment by c-moss-talk** [comment]
> Figure out how to pass through and combine HTTP
perhaps this tool might be useful?
https://www.apollographql.com/docs/apollo-server/federation/introduction/
I'd be happy to look into this -- currently familiarizing myself with 4.0 codebase 👍

**Comment by goloroden** [comment]
@c-moss-talk Thanks for the hint!

I think @yeldiRium already had a (first) look at this, so he's probably the right one to answer here.

When we are going to talk to each other next week, maybe we can talk about this a little bit, too.

I'm curious on your feedback on 4.0 CTP 1 😊
