### ISSUE TITLE
Add a CLI command to (re)create the deployment scripts

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#546]
### What is this feature about?

Sometimes, people delete the `deployment` folder, or they don't even have it, e.g. because they migrated an old application from wolkenkit 3.x. For these scenarios, it would be helpful if there was an easy way to (re)create the deployment scripts using the CLI.

### What needs to be done to implement this feature?

- [x] Add a new `create-deployment` command
  - [x] Deny to work if the `deployment` directory already exists
  - [x] Let the user override the existing directory with the `--force` flag
- [x] Add tests

### What else should we know?

Supposed the user provides the `--force` flag, we still need to clarify what to do with existing files. Overwrite them, or backup them, or just ignore them?

**Comment by yeldiRium** [comment]
After a bit of consideration, I don't think the command should stop working if the `deployment` directory already exists.

If I'm only interested in certain manifests, I'll delete the rest after they are initially created. If I then edit the manifests I'm interested in and later realize, that I'd like to see the others too, then I have no way to only create the missing manifests.

Thus I think the command should create all missing files and optionally (with a `--force` flag) overwrite the existing files.
So the decision making is not based on the existence of the deployment folder (which may contain only part of the manifests) but on the existence of the individual manifests.

@goloroden: What do you think about this?

**Comment by goloroden** [comment]
Hmmmm 🤔 

I'm not convinced yet. Many people will only use a single manifest, and recreating all of them, and then having to delete all of them except two (the original one, and the new one) seems a bit cumbersome.

What about this approach:

- The command uses `deployment` as the default folder. If it already exists, it won't work to avoid overwriting, and to avoid having a somewhat merged state where you need to pick the ones you want to delete individually (which, as lined out, may be some work).
- Optionally, you can provide a path to a folder, similar to the `init` command. If you provide a non-existent directory, it gets created, and things happen as if the user would run the `init` command. If it already exists, see above.

This way, you could more easily compare the auto-generated ones with your custom ones, and you could pick a single one you want to keep, and then delete the entire folder.

What do you think?

**Comment by yeldiRium** [comment]
> This way, you could more easily compare the auto-generated ones with your custom ones, and you could pick a single one you want to keep, and then delete the entire folder.

That makes sense. My approach was more directed towards getting the other manifests, that one does not yet use, rather than getting the generated versions of the manifests one is using and has edited.

If that is the goal, your approach sounds better.

**Comment by goloroden** [comment]
Well, I think it depends 😉 

However, even if you want to get an additional one you are not yet using, I assume that typically you are only interested in a single one. For that scenario, I think it's easier to copy over a single file from the new folder, and then delete the new folder, than to have to sort out all the ones you actually don't need. But as said, this is only guessing.

Shall we simply try it like this, and then wait for feedback to come?
