### ISSUE TITLE
Stateful flows run too often

### ISSUE THREAD

**Issue by zibur** [thenativeweb/wolkenkit#56]
### What is this bug about?

Statefull flow with 2 transitions that listen to the same event. 

### What steps are needed to reproduce the bug?

- Create new wolkenkit project with 'wolkenkit-template-chat'
- Add this flow

```
'use strict';

const identity = {
    'communication.message.liked': event => event.aggregate.id,
};

const initialState = {
    is: 'pristine',
};

const transitions = {
    pristine: {
        'communication.message.liked'(flow, event) {
            console.log('eventId:', event.id);
        }
    },
    magic: {
        'communication.message.liked'(flow, event) {}
    }
};

const reactions = {
    pristine: {
        magic(flow, event, {app}) {}
    },
    magic: {
        magic(flow, event, {app}){}
    }
};

module.exports = {identity, initialState, transitions, reactions};
```

### What is the expected result?
`console.log` should be called once with the event.id

### What is the actual result?
`console.log` get called 2 times for every liked event

### What else should we know?
When you remove the magic transistion `console.log` is colled once for every liked event.
getClassifiedFlows creates two instances of the same statefull flow, where both react to the same event.

**Comment by goloroden** [comment]
Since we are currently heavily working on 4.0, and 4.0 will be a complete rewrite from scratch, it's questionable whether this behavior still occurs. Hence I'm closing this for now.
