### ISSUE TITLE
Improve error messages when prerequisites are missing

### ISSUE THREAD

**Issue by radumaerza** [thenativeweb/wolkenkit#58]
### What is this feature about?
I would extend the CLI Information Message by echoing  "Docker Client missing - did you install the Docker Application on your Machine?" when he tries the run the "wolkenkit start" command, to tell the user that he is missing something.

I would also additionally create a "Prerequisites" category for https://github.com/thenativeweb/wolkenkit. (if there are more prerequisites required to work with wolkenkit)

### What needs to be done to implement this feature?

- [x] Change the line of code, that prints the "Docker client is not installed." to "Docker client is not installed. (see https://docs.wolkenkit.io/2.0.0/getting-started/installing-wolkenkit/verifying-system-requirements/ for how to install wolkenkit). "
- [x] Change the line of code, that prints the "Git is not installed." to "Git is not installed. (see https://docs.wolkenkit.io/2.0.0/getting-started/installing-wolkenkit/verifying-system-requirements/ for how to install wolkenkit). "
- [ ] Add the Prerequisites Category under https://docs.wolkenkit.io/2.0.0/getting-started/installing-wolkenkit/verifying-system-requirements/

**Comment by goloroden** [comment]
Thanks for setting up this issue 😊 

Sounds great so far, I'd only have one thing you might do before starting to work on the PR: Could you please check in the CLI's code whether there are additional prerequisites we check for (I think so, but I'm not sure without checking the code by myself), and if so, update this issue accordingly?

Apart from that, regarding the error message: The current one says:

> Docker client is not installed.

I'd like to keep it this way, but adding a simple "did you install Docker" sounds a little bit strange here, as it had already been said, that it's not installed 😉 

Maybe a better idea would be to have something such as:

> Docker client is not installed (see https://docs.wolkenkit.io/2.0.0/getting-started/installing-wolkenkit/verifying-system-requirements/ for how to install wolkenkit).

What do you think about this?

**Comment by radumaerza** [comment]
I've been checking the code and the only prerequisites currently are Git and Docker.

I think the idea is good, that those 2 messages point to  https://docs.wolkenkit.io/2.0.0/getting-started/installing-wolkenkit/verifying-system-requirements/ which will contain the prerequisites category.

**Comment by goloroden** [comment]
Great 👍 

Could you then please update the `What needs to be done to implement this feature?` section in the first part of this issue? And, apart from that, I'm looking forward to your PR 😊

**Comment by radumaerza** [comment]
> * [ ]  Add the Prerequisites Category under https://docs.wolkenkit.io/2.0.0/getting-started/installing-wolkenkit/verifying-system-requirements/

This feature won't get implemented for the reason that there already are sections that describe the prerequisites. (see https://docs.wolkenkit.io/2.0.0/getting-started/installing-wolkenkit/installing-on-windows/)
