### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by noTruth** [thenativeweb/wolkenkit#6]
Plans to make it open source? 😊

**Comment by goloroden** [comment]
It actually is 😊 

See [this section](https://github.com/thenativeweb/wolkenkit#finding-the-code) for details on how to find the code.

The only part that is currently not open-source is the CLI, but we are working hard on changing this.

**Comment by noTruth** [comment]
Yeah, I looked all the parts. But wolkenkit cli module provides closed infrastructure (I can not affect the Docker build/up etc.) and I don't see the point of using it in production 😔. About separate modules: they are partially tied for use with wolkenkit, and I do not really understand how to use them without wolkenkit... For example: https://github.com/reimagined/resolve provides individual parts of this model, and it's easy to use for any tasks. But they have a bad code, and not a tasty architecture 😂 (IMHO). Your read/write models, stateless/stateful flows are awesome 👍. I think these models would be cool to use for microservices. Like:
`
const wolkenkitBroker = wolkenkit.createBroker({
  eventStore: /* ... */,
  eventBus: /* ... */
})
wolkenkitBroker.statelessFlow({
  name: 'simple',
  when: {/* ... */}
})
// ...
wolkenkitBroker.testContext.testAggregate().testCommand({/* ... */})
`
I would like to know your opinion on this matter. Thank u :)

PS: in advance, I'm sorry if that. I may not know something 😊

**Comment by goloroden** [comment]
@noTruth IIRC you had another comment here with questions, that I wanted to answer now, and now it is gone… have your questions already been answered?

**Comment by noTruth** [comment]
Yes. All good)
