### ISSUE TITLE
Discuss whether to further support MongoDB in the event store

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#65]
### What is this concept about?

So far, we marked MongoDB support as experimental in the [wolkenkit-eventstore](https://github.com/thenativeweb/wolkenkit-eventstore) module. The reason for this is that MongoDB does not support transactions, which are needed to guarantee an all-or-nothing semantics when saving multiple events. Now MongoDB 4.0 introduced transaction support, but only for clusters. We should define whether we further want to support MongoDB 4.0, or if we get rid of it (since relational databases seem to be a better fit for event stores anyway than NoSQL databases).

### What issues need to be clarified to complete this concept?

- [x] Is transaction support planned for MongoDB in single-instance setups for a version > 4.0?
- [x] Do we want to support MongoDB as an event store?

**Comment by goloroden** [comment]
Transactions currently (4.0) only work with [replica sets](https://docs.mongodb.com/manual/core/transactions/#transactions-and-replica-sets). An example for this can be found [here](https://thecodebarbarian.com/a-node-js-perspective-on-mongodb-4-transactions.html#transferring-money-between-accounts-in-node-js).

**Comment by tomwidmer** [comment]
Note that single-member replica sets are trivial to set up - run `mongod --replSet <some name>` then do something like `mongo --eval "rs.initiate()"`. You also need this to get access to the change streams API, which makes streaming events simple. The thing required for transactions/change streams isn't multiple servers, it's the 'oplog', and you get that with a single server replica set.

**Comment by goloroden** [comment]
@tomwidmer Ah, that's good to know, thanks a lot for the hint 😊 

Then we could implement this without too much effort.

**Comment by goloroden** [comment]
We decided to continue supporting MongoDB, and we will move to 4.0.
