### ISSUE TITLE
Rate limit the API

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#72]
### What is this feature about?

We might rate limit the API using a module such as [express-brute](https://www.npmjs.com/package/express-brute) (or something similar, this is just a suggestion, not a specifically chosen module).

### What needs to be done to implement this feature?

- [ ] Add rate-limiting to the various endpoints
- [ ] Clarify how to do this for websocket connections
- [ ] Add tests

### What else should we know?

This will probably need to be done inside of the [tailwind](https://github.com/thenativeweb/tailwind) module, maybe somewhere around [here](https://github.com/thenativeweb/tailwind/blob/dc991130ee507d7f75744bad879e2e861c1f818b/src/wires/status/http/Server.js#L48-L70).

**Comment by radumaerza** [comment]
I would like to solve this issue :)

**Comment by goloroden** [comment]
@radumaerza Thanks, I'm looking forward to what you come up with. Unfortunately, I can't assign the issue to you, but I have added the `In progress` label to point out that this issue is being worked on.

**Comment by goloroden** [comment]
This will be solved as part of #78
