### ISSUE TITLE
Support private modules in wolkenkit applications

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#79]
### What is this feature about?

When starting a wolkenkit application, we run `npm install` internally. Right now this runs as anonymous, which means that you can only install publicly available modules. To support private modules, the user would need to login to npm first. We could ask the user to provide an npm token, which we then use internally to run `npm install`.

### What needs to be done to implement this feature?

- [ ] Introduce a way for the user to provide the token
- [ ] Use the token when running `npm install`
- [ ] Add tests
- [ ] Add documentation

**Comment by grundhoeferj** [comment]
Here are my first thoughts about the configuration:
```json
{
  ...
  "wolkenkit": {
    "environments": {
      "default": {
        "api": {
          ...
        },
        "npm": {
          "token": "00000000-0000-0000-0000-000000000000"
        }
      },
      ...
    }
  }
}
```
If we can provide the token configuration via `package.json`, we can also use our `wolkenkit-secrets.json` there - i think this is great benefit.

To get the token within the build process (docker), we should introduce a `--build-arg` for that, called `NPM_TOKEN`. This argument will be available on build time. Now we have to create the `.npmrc` file including the given token (`NPM_TOKEN`) and start `npm install`. Inspired by: https://docs.npmjs.com/docker-and-private-modules

Here you will find information about creating the token: https://docs.npmjs.com/creating-and-viewing-authentication-tokens

**Comment by radumaerza** [comment]
I will take a look and see if I can create this feature.

**Comment by goloroden** [comment]
A simple solution would be to copy over a `.npmrc` file if there is one. However, one needs to pay attention to not keeping this file in the final Docker images for security reasons, so you need to think about multi-stage builds, squashing images, or something like that…

**Comment by goloroden** [comment]
Since the new CLI now respects a `.npmrc` file in the local application's folder, this is supported from 4.0 onwards 😊
