### ISSUE TITLE
Add a guide on how authentication works

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#80]
### What is this feature about?

Currently, we don't have a single guide to describe how to setup authentication. Using the blog post that we have written for Auth0 as a foundation, it should be pretty simple to setup such a guide. Additionally, [this check list](https://stackoverflow.com/a/48266737/1333873) on StackOverflow might be helpful.

### What needs to be done to implement this feature?

- [ ] Write the guide
- [ ] Add it to the documentation

### What else should we know?

@schmuto has indicated interest on this, so we should inform him once this has been done.

**Comment by co16353sidak** [comment]
hey, @goloroden would like to work on this as my first issue here, please give the go ahead. 🥇

**Comment by goloroden** [comment]
@co16353sidak Sounds great, thanks for your interest 😊

I think the second half of https://auth0.com/blog/building-real-time-web-applications-using-wolkenkit/ is really helpful, and a good source. Since that was written by me, we could also reuse some of the text without having a rights problem. 

What do you need to get started?

**Comment by co16353sidak** [comment]
@goloroden What do you feel is the most suitable place to add this article in the documentation

**Comment by goloroden** [comment]
I think putting it into the existing `Guides` section makes sense: https://github.com/thenativeweb/wolkenkit-documentation/tree/master/lib/docs/latest/guides

Please note to make the new guide appear in the navigation, you also have to adjust the metadata of the documentation: https://github.com/thenativeweb/wolkenkit-documentation/blob/master/lib/docs/latest/metadata.js#L44-L52

**Comment by co16353sidak** [comment]
Great, let me create a first draft and submit a PR.
P.S :- I will be  using your article as a direct reference.

**Comment by goloroden** [comment]
Sounds great 👍 

And regarding the article, feel free to use its text. As said, since it was written by me, this shouldn't be a problem.

**Comment by co16353sidak** [comment]
Please review @goloroden

**Comment by goloroden** [comment]
Will be part of the 4.0 documentation.
