### ISSUE TITLE
Ensure that domain events are published sequentially by the domain server

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#852]
### What is this task about?

We need to ensure that the domain server publishes any domain events in sequential order, and not concurrently, to ensure that they arrive in order at the publisher.

### What needs to be done to complete this task?

- [x] Verify whether domain events are published sequentially and in order
- [ ] If not, fix this

**Comment by yeldiRium** [comment]
I've checked both the domain server in the microservice runtime and the single process runtime and all domain events are published sequentially.
