### ISSUE TITLE
Describe the HTTP and web socket endpoints

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#88]
### What is this feature about?

With tailwind, we have created a standard for how to send commands, wait for events and query read models. We should describe this in the documentation, since from time to time people are interested in how to access a wolkenkit application directly, i.e. without using the client SDK.

### What needs to be done to implement this feature?

- [ ] Add a page on the HTTP API
- [ ] Add a page on the web socket API

### What else should we know?

This was asked by @schmuto, so we should inform him once this has been done.

**Comment by yeldiRium** [comment]
OpenAPI/Swagger probably won't be suitable for this, since command and query each have one http endpoint with varying payloads. So an OpenAPI spec would have only two endpoints with massive schemas each.

We need to find an individual solution for this.

**Comment by goloroden** [comment]
On the one hand, meanwhile we have introduced an OpenAPI and a GraphQL endpoint, which help here, on the other hand this will be part of the new documentation for 4.0. Hence closed.
