### ISSUE TITLE
Think of new name for AggregateInstance.exists()

### ISSUE THREAD

**Issue by yeldiRium** [thenativeweb/wolkenkit#918]
### What is this task about?

The `AggregateInstance.exists()` function is not as intuitive as it could be. Its return value describes whether any events for the `AggregateInstance` exist. We should think of a better name for it.

So far contenders are:

- `hasHistory`
- `isNew`
- `isPristine`
- `hasEvents`

### What needs to be done to complete this task?

- [x] think of a name
- [x] use it

**Comment by goloroden** [comment]
We've decided to go for `isPristine` 😊
