### ISSUE TITLE
Add TypeScript types

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#92]
### What is this feature about?

Since we have been asked a few times by now, it would be great if we had TypeScript types to improve support for TypeScript users. Basically, this affects two things:

1. The types exposed by wolkenkit
2. The types exposed by the application you define

While the first ones could be created statically, the second ones would need to be defined dynamically.

### What needs to be done to implement this feature?

- [x] Add static type definitions for types exposed by wolkenkit
- [x] Add dynamic type definitions for types exposed by the application you define

**Comment by gossi** [comment]
I started with this yesterday night. See here: https://github.com/gossi/spomoda/tree/master/server/types

I mainly focused on the static types here (even I thinkt, they are not complete). I enabled dynamic ones... but didn't check them. In TS you can do sth like:

```ts
type Context = {
  // current, allows all keys to be an aggregate
  [key: string]: (id?: string) => Aggregate;
  // allow only allowed keys:
  [key: keyof Foo]: (id?: string) => Aggregate;
}
```

though, that `Foo` I don't know where to get from. Apart from that, finishing the static types first and later constrain the dynamic ones are a good idea. I'm happy to contribute my types, though they should be solid, because broken types are worse than no types!

**Comment by beenotung** [comment]
@gossi There is a bug in the typescript compiler / tslint that only allows using string or number for index, despite it should allow types that are subset of string, For example
```typescript
type Context<ContextType extends string> = {
  [contextType: ContextType]: any
}
```
Will cause an error of `TS1023: An index signature parameter type must be 'string' or 'number'.
`

**Comment by beenotung** [comment]
@gossi In your case,
For strong type support, you may use Map instead of raw object, otherwise, it require some hack like
```typescript
export type Aggregate = {
  type: string
};

export interface Context<ContextType extends string, A extends Aggregate> {
  (contextType: ContextType): (id?: string) => A
}

export type DemoContextType = 'messaging' | 'booking';
export type DemoAggregate = Aggregate;

let demoContextMap = new Map<DemoContextType, (id?: string) => DemoAggregate>();

export let DemoContext = new Proxy({} as Context<DemoContextType, DemoAggregate>, {
  get(target: Context<DemoContextType, DemoAggregate>, p: PropertyKey, receiver: any): any {
    if (typeof p === 'string' && demoContextMap.has(p as DemoContextType)) {
      return demoContextMap.get(p as DemoContextType);
    }
    return Reflect.get(target, p, receiver);
  },
  apply(target: Context<DemoContextType, DemoAggregate>, thisArg: any, argArray?: any): any {
    if (Array.isArray(argArray) && argArray.length === 1 && demoContextMap.has(argArray[0])) {
      return demoContextMap.get(argArray[0]);
    }
    return Reflect.apply(target, this, argArray);
  },
});

let m1 = DemoContext('messaging')('m1');
// no compile error

let foo1 = DemoContext('foo')('f1');
// compile error TS2345: Argument of type '"foo"' is not assignable to parameter of type 'DemoContextType'.
```
But you can see using Map will be much simpler.
One may make a Typescript wrapper on top of the wolkenkit Javascript code base.

**Comment by goloroden** [comment]
FYI: https://wolkenkit.slack.com/archives/CC412DDFU/p1563728982002500

**Comment by goloroden** [comment]
wolkenkit v4 will have first-class TypeScript support. For an example see [this application](https://github.com/thenativeweb/wolkenkit/tree/5349b1c19de79922bbdb11f46dab46d71e169f34/__temp__/sampleApplicationWithTypeScript).

With it, you get perfect type support in your editor / IDE 😊
