### ISSUE TITLE
Move test-related exports into separate file

### ISSUE THREAD

**Issue by yeldiRium** [thenativeweb/wolkenkit#928]
Currently we export `sandbox` in the `wolkenkit.ts` with all the other development utilities.

We should export those from a separate file so that they can be imported via `import from 'wolkenkit/test`.

**Comment by yeldiRium** [comment]
There seems to be no way to either configure multiple entrypoints to an npm package or to set a base path from which import paths should be resolved. so to make `import {} from 'wolkenkit/test';`  work, there would have to be a `test.js` in the root directory of the published package.

I don't think that's feasible with our current setup, so I'd leave this as-is.

What do you think, @goloroden?

**Comment by goloroden** [comment]
Agreed 👍
