### ISSUE TITLE
Provide a sandbox for flows

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#987]
### What is this feature about?

In order to be able to test flows, we should have a sandbox similar to the one we have for aggregates. Ideally, the foundation for both is the same, and we simply add different methods for both.

### What needs to be done to implement this feature?

- [x] Add a sandbox for flows
- [x] Integrate the sandbox with the one for aggregates
- [x] Add tests

**Comment by yeldiRium** [comment]
TODO regarding #999: Split the sandboxes into three files. One for the common configuration in the beginning and then splitting off into an aggregate-sandbox and a flow-sandbox.
