### ISSUE TITLE
Add information on licensing

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#99]
### What is this feature about?

Right now we don't have any information on licensing in the documentation. However, we could explain a number of things there. Hence, we should change this. A good extension point might be *Getting started > Understanding wolkenkit > Licensing*

### What needs to be done to implement this feature?

- [ ] Answer the following questions
  - [ ] Why did we choose AGPL 3.0?
  - [ ] What does AGPL mean for the user?
  - [ ] How can open-source be sustainable?
- [ ] When do you need the enterprise edition?

**Comment by goloroden** [comment]
# Licensing

We've collected a set of questions and answers to clarify all the licensing and legal issues when creating wolkenkit applications.

## What is the license of wolkenkit?

We at the native web believe that wolkenkit transforms the way we develop cloud-native applications. We also believe in the benefits of [free software](https://en.wikipedia.org/wiki/The_Free_Software_Definition): Getting access to modify the software, preventing vendor lock-in and providing a basis for a vital and open community. This is why we have licensed the Community Edition of wolkenkit using GNU Affero General Public License, Version 3 (AGPLv3) published by the Free Software Foundation.

To also create a sustainable business that reliably backs the open-source model we additionally offer wolkenkit using a proprietary license. For us, open-source and business are not contradictory, but rather form a respectful partnership to create better software.

All of wolkenkit core modules are licensed under AGPLv3. The modules that you use to interact with a wolkenkit application through its API are licensed under the GNU Lesser General Public License, version 3 (LGPLv3).

## If I write a wolkenkit application, do I have to license it under the AGPLv3?

Yes, if you're using the Community Edition. A wolkenkit application is a derivative work of wolkenkit. If you distribute it, you must do so under the terms of the AGPL version 3.

## Can I sell or charge for a wolkenkit application?

Yes, even if you're using the Community Edition. However, you must distribute it under the AGPL version 3 or later, so those you sell it to must be allowed to modify and redistribute it as well.

## Is there a proprietary license available for wolkenkit?

Yes. <a href='mailto:hello@thenativeweb.io'>Contact us</a> to discuss your particular use case for a proprietary licensed version.

## If I publish a client/website using the wolkenkit client SDK, do I have to license it under the AGPLv3 as well?

No. [wolkenkit-client-js](https://github.com/thenativeweb/wolkenkit-client-js) is licensed under GNU Lesser General Public License, version 3 (LGPLv3). Therefore you do not have to publish your client code under the same conditions. You do not have to provide its source code.

## Something missing here?

Feel free to <a href='mailto:hello@thenativeweb.io'>contact us</a> if there important aspects missing in this list.

**Comment by co16353sidak** [comment]
@goloroden would like to work on this, seems like a simple PR and could help me understand this repo a lot more in the process.

**Comment by goloroden** [comment]
@co16353sidak Thanks for your interest here 😊

I agree with you that technically speaking this should be quite easy to do, but not regarding the content. 

Many of this would need to be about the choices we made at the native web, and that is something only we can explain for obvious reasons. 

Nevertheless it would be great to have a starting point. So if you want to suggest something here, I would be more than happy, but just to have said it: It may be that we will change a *lot* of it. If this doesn’t discourage you, let’s go 😊

**Comment by jbeaudoin11** [comment]
Hey @goloroden , I have some question related to this !

> If I write a wolkenkit application, do I have to license it under the AGPLv3?
Yes, if you're using the Community Edition. A wolkenkit application is a derivative work of wolkenkit. If you distribute it, you must do so under the terms of the AGPL version 3.

How could this apply for an internal tool ? We do not distribute it to the general public, it's a "private software" that only our employees will use.

I'm pretty sure I'm right to say that we can use wolkenkit CE under these circumstances. I did some research and this is what i found that led my to this conclusion.


## GPL and internal software
Yes this is about GPL, AGPL if i'm not mistaken, the only difference is the section 13 `Remote Network Interaction`

#### Using GPL 3rd party code for internal closed source project [closed]
https://stackoverflow.com/questions/1492687/using-gpl-3rd-party-code-for-internal-closed-source-project
> This question is specifically addressed in the GPL FAQ, and it says you're allowed to use GPLed software inside a company without legally distributing it. You have no obligation to release either source or binary outside the company.

http://www.gnu.org/licenses/gpl-faq.en.html
#### Is making and using multiple copies within one organization or company “distribution”?

> No, in that case the organization is just making the copies for itself. As a consequence, a company or other organization can develop a modified version and install that version through its own facilities, without giving the staff permission to release that modified version to outsiders.
>
> However, when the organization transfers copies to other organizations or individuals, that is distribution. In particular, providing copies to contractors for use off-site is distribution.

## AGPL Link 1

## AGPL Link 2
https://opensource.com/article/17/1/providing-corresponding-source-agplv3-license

> What is often misunderstood is that the source code requirement in AGPLv3 Section 13 is triggered only where the AGPLv3 software has been modified by "you" (for example, the entity providing the network service). My interpretation is that, so long as "you" do not modify the AGPLv3 code, the license should not be read as requiring access to the Corresponding Source in the manner prescribed by Section 13. As I see it, many unmodified and standard deployments of software modules under AGPL simply do not trigger Section 13, although making the source code available even if not required under the license is a good idea.

When you said :
> A wolkenkit application is a derivative work of wolkenkit
To me it sounds like you are implying that we modify wolkenkit by using it ? No offence but i wonder how is that a "legit" statement ?

**Comment by goloroden** [comment]
@jbeaudoin11 You're right about the distinction between GPL and AGPL, their only difference is the networking aspect. Hence, [this answer](https://www.gnu.org/licenses/gpl-faq.html#InternalDistribution) should match AGPL as well:

> No, in that case the organization is just making the copies for itself. As a consequence, a company or other organization can develop a modified version and install that version through its own facilities, without giving the staff permission to release that modified version to outsiders.
>
> However, when the organization transfers copies to other organizations or individuals, that is distribution. In particular, providing copies to contractors for use off-site is distribution.

So, yes, you should be fine with internal usage, without making the sources public. Please note that I am not a lawyer, but from my understanding of the license I'd agree with your result.

Generally speaking, if you want to write down our intention as a single sentence, it would be:

> If you make the world a better place by doing open-source, we help you make the world a better place by providing open-source. If you make money (which is perfectly fine) with out work, we would like to have some piece of the cake, too.

Now, you said:

> In the end, I'm not here to make money with our software, it's really just an internal software (and a school project) that hopefully will make us save money.

To me, this definitely sounds like "making the world a better place", and especially if it's only for in-house usage, I don't see a problem here. If you want to be on the very safe side legally, please feel free to [contact us](mailto:hello@thenativeweb.io), and we'll figure out a specific license for your case

> At the same time, as an individual, i'm really interested by the framework and how impressive it is. I think there is some quirk here and there and might help it evolve in the future.

Thanks for the nice feedback, and of course we would be more than happy to welcome you as a contributor 😊 

Oh, and finally: You asked about:

>> A wolkenkit application is a derivative work of wolkenkit
>
> To me it sounds like you are implying that we modify wolkenkit by using it ? No offence but i wonder how is that a "legit" statement ?

This is what our lawyers have come up with, since they argued that a wolkenkit application is like a plugin for wolkenkit itself, as the application gets loaded into the surrounding framework (don't take this literally, I'm just trying to repeat it from out of my head), and that's why an application is considered a derivative work. I am definitely the wrong person to discuss the details here, but that's the rough idea behind this sentence. Hope this clarifies it 😊

**Comment by jbeaudoin11** [comment]
Thank you, we are all relief by that ! 

For now, we will stay with the current Licence. It's my way to make sure what we make wont be commercialized w/o open sourcing it when I'm gone ;).

**Comment by goloroden** [comment]
Will be part of the 4.0 documentation.

**Comment by idealley** [comment]
We need to publish our software under Apache 2, so if I understand correctly, Wolkenkit is out for us :( 

Anyway to have a compatible licence?

**Comment by goloroden** [comment]
@idealley Can you please contact me via email? My mail address is *golo dot roden at thenativeweb dot io*.

I'm sure we can figure out something that works for you 😊
